"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.color.color import Color
from borb.pdf.layout_element.layout_element import LayoutElement

"""
Represents a circular process layout that visually organizes a series of steps or items in a looped, radial arrangement to emphasize cyclic or continuous progression.

This class is designed to display items evenly distributed around a circle,
visually reinforcing the concept of repetition, feedback loops, or perpetual flow.
Each item represents a step or stage in the process, with arrows or connectors
indicating directionality—typically clockwise. This layout is ideal for systems
that repeat, evolve in stages, or emphasize closed-loop structures such as life
cycles, iterative processes, or circular economies.
"""
class CircularProcess:
    """
    Represents a circular process layout that visually organizes a series of steps or items in a looped, radial arrangement to emphasize cyclic or continuous progression.

    This class is designed to display items evenly distributed around a circle,
    visually reinforcing the concept of repetition, feedback loops, or perpetual flow.
    Each item represents a step or stage in the process, with arrows or connectors
    indicating directionality—typically clockwise. This layout is ideal for systems
    that repeat, evolve in stages, or emphasize closed-loop structures such as life
    cycles, iterative processes, or circular economies.
    """
    @staticmethod
    def build(level_1_items: typing.List[str], background_color: Color = ..., level_1_font_color: Color = ..., level_1_font_size=...) -> LayoutElement:
        """
        Construct a circular process layout with items arranged radially around a center.

        This static method creates a visual layout of a process, placing each
        item (level 1) evenly spaced around a circle to represent cyclical flow
        or repeating sequences. Arrows connect items in a clockwise direction,
        emphasizing the ongoing, looped nature of the process.

        :param level_1_items:       A list of strings representing the primary items or steps in the process.
        :param background_color:    The background color for the layout. Defaults to X11Color.PRUSSIAN_BLUE.
        :param level_1_font_color:  The font color for item labels. Defaults to X11Color.WHITE.
        :param level_1_font_size:   The font size for item labels. Defaults to 12.
        :returns: A LayoutElement representing the constructed circular process layout, ready for rendering in a graphical interface.
        """
        ...
    


