"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.color.color import Color
from borb.pdf.layout_element.layout_element import LayoutElement

"""
Represents a horizontal layout for visualizing a process with steps, each accompanied by a pie chart that indicates progress.

This class allows the creation of a clear representation of a multistep
process, where each step is visually marked and supplemented by a pie
chart reflecting the percentage of completion. The first step begins with
an empty pie chart, while subsequent steps can show varying levels of
progress, such as 50% for the second step and 100% for the final step.
This intuitive layout aids in understanding the flow and status of the
overall process at a glance.
"""
class HorizontalPieProcess:
    """
    Represents a horizontal layout for visualizing a process with steps, each accompanied by a pie chart that indicates progress.

    This class allows the creation of a clear representation of a multistep
    process, where each step is visually marked and supplemented by a pie
    chart reflecting the percentage of completion. The first step begins with
    an empty pie chart, while subsequent steps can show varying levels of
    progress, such as 50% for the second step and 100% for the final step.
    This intuitive layout aids in understanding the flow and status of the
    overall process at a glance.
    """
    @staticmethod
    def build(level_1_items: typing.List[str], level_2_items: typing.List[typing.List[str]], background_color: Color = ..., level_1_font_color: Color = ..., level_1_font_size: int = ..., level_2_font_color: Color = ..., level_2_font_size: int = ...) -> LayoutElement:
        """
        Construct a horizontal process layout with steps, each accompanied by a pie chart indicating progress.

        This static method builds a visual representation of a multistep
        process. Each step (level 1 item) is displayed alongside a corresponding
        set of details (level 2 items) and a pie chart that illustrates the
        progress for that step. The method allows customization of background
        color, font colors, and font sizes for both levels, providing a clear
        and aesthetically pleasing layout.

        :params: level_1_items:         A list of strings representing the main steps in the process.
        :params: level_2_items:         A list of lists, where each sub-list contains strings providing additional details or sub-steps related to each main step.
        :params: background_color:      The background color for the layout. Defaults to X11Color.PRUSSIAN_BLUE.
        :params: level_1_font_color:    The font color for the main step items. Defaults to X11Color.WHITE.
        :params: level_1_font_size:     The font size for the main step items. Defaults to 16.
        :params: level_2_font_color:    The font color for the sub-step items. Defaults to X11Color.WHITE.
        :params: level_2_font_size:     The font size for the sub-step items. Defaults to 14.
        :returns:                       A LayoutElement representing the constructed horizontal process layout, suitable for rendering in a graphical interface.
        """
        ...
    


