"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.color.color import Color
from borb.pdf.layout_element.layout_element import LayoutElement

"""
Represents an inverted pyramid layout that organizes items hierarchically, with each level displayed as a centered row.

This class is designed to create a structured inverted pyramid presentation where
items are displayed in rows that progressively narrow toward the base, forming an
upside-down pyramid shape. The layout allows customization of colors, font size,
and alignment to enhance the visual appeal and readability. The inverted pyramid format
is ideal for illustrating concepts such as diminishing priorities, funnel processes,
or narrowing stages in workflows or data presentations.
"""
class InvertedPyramid:
    """
    Represents an inverted pyramid layout that organizes items hierarchically, with each level displayed as a centered row.

    This class is designed to create a structured inverted pyramid presentation where
    items are displayed in rows that progressively narrow toward the base, forming an
    upside-down pyramid shape. The layout allows customization of colors, font size,
    and alignment to enhance the visual appeal and readability. The inverted pyramid format
    is ideal for illustrating concepts such as diminishing priorities, funnel processes,
    or narrowing stages in workflows or data presentations.
    """
    @staticmethod
    def build(level_1_items: typing.List[str], background_color: Color = ..., level_1_font_color: Color = ..., level_1_font_size=...) -> LayoutElement:
        """
        Build an inverted pyramid layout as a `LayoutElement` with the given items and appearance settings.

        This method creates a hierarchical inverted pyramid structure where each item is displayed
        in a centered row. The rows progressively narrow toward the base, forming the shape of an upside-down pyramid.
        The visual appearance can be customized with parameters such as background color, font color, and font size.

        :param level_1_items: A list of strings representing the items to include in the inverted pyramid. Each string corresponds to a row, starting from the widest row at the top.
        :param background_color: The background color for the pyramid rows. Defaults to `X11Color.PRUSSIAN_BLUE`.
        :param level_1_font_color: The font color for the text in the pyramid. Defaults to `X11Color.WHITE`.
        :param level_1_font_size: The font size for the text in the pyramid. Defaults to `12`.

        :return: A `LayoutElement` representing the inverted pyramid structure, ready to be added to a PDF.
        """
        ...
    


