"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.color.color import Color
from borb.pdf.layout_element.layout_element import LayoutElement

"""
Represents a layout for visually contrasting two opposing ideas or concepts, with directional arrows emphasizing the contrast.

This class arranges items in two levels, where each level represents one side
of the opposing ideas. The layout consists of an "arrow down" symbol pointing
to the first level of items, and an "arrow up" symbol pointing to the second
level. This structure highlights differences or opposing perspectives between
the two levels, making it ideal for comparing concepts, options, pros and cons,
or other dual aspects.
"""
class OpposingIdeas:
    """
    Represents a layout for visually contrasting two opposing ideas or concepts, with directional arrows emphasizing the contrast.

    This class arranges items in two levels, where each level represents one side
    of the opposing ideas. The layout consists of an "arrow down" symbol pointing
    to the first level of items, and an "arrow up" symbol pointing to the second
    level. This structure highlights differences or opposing perspectives between
    the two levels, making it ideal for comparing concepts, options, pros and cons,
    or other dual aspects.
    """
    @staticmethod
    def build(level_1_items: typing.List[str], level_2_items: typing.List[typing.List[str]], background_color: Color = ..., level_1_font_color: Color = ..., level_1_font_size: int = ..., level_2_font_color: Color = ..., level_2_font_size: int = ...) -> LayoutElement:
        """
        Construct an "opposing ideas" layout, visually contrasting two sets of ideas with directional arrows emphasizing the distinction.

        This static method arranges items in two levels to visually represent
        opposing concepts or ideas. Each item in `level_1_items` corresponds to
        an item in `level_2_items`, with an arrow pointing down towards the
        first level and an arrow pointing up towards the second, emphasizing
        the contrast between the two. Customization options for colors and
        font sizes allow for adapting the layout to different visual themes.

        :param level_1_items: A list of strings representing the first set of items or ideas (Level 1).
        :param level_2_items: A list of lists, where each sub-list contains strings for the corresponding items in the second set (Level 2).
        :param background_color: The background color for the layout. Defaults to X11Color.PRUSSIAN_BLUE.
        :param level_1_font_color: The font color for Level 1 items. Defaults to X11Color.WHITE.
        :param level_1_font_size: The font size for Level 1 items. Defaults to 16.
        :param level_2_font_color: The font color for Level 2 items. Defaults to X11Color.WHITE.
        :param level_2_font_size: The font size for Level 2 items. Defaults to 14.
        :return: A LayoutElement representing the constructed "opposing ideas" layout, suitable for rendering in a graphical interface.
        """
        ...
    


