"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.color.color import Color
from borb.pdf.layout_element.layout_element import LayoutElement

"""
Represents a vertical equation layout that displays a preset equation format: "A + B + C ... = D".

This class provides a visual layout specifically designed to represent
an equation in which the components "A", "B", "C", etc., are user-defined
inputs, while the operators "+" and "=" remain fixed. Users can configure
the items on either side of the equation, but cannot change the equation
structure or operators.

The layout is ideal for scenarios where specific inputs need to be summed
or combined to produce a result, and is commonly used in educational,
financial, or analytical presentations. Customization options are available
for background color, font colors, and font sizes for each component,
allowing for visual adaptation to fit specific themes or presentation needs.
"""
class VerticalEquation:
    """
    Represents a vertical equation layout that displays a preset equation format: "A + B + C ... = D".

    This class provides a visual layout specifically designed to represent
    an equation in which the components "A", "B", "C", etc., are user-defined
    inputs, while the operators "+" and "=" remain fixed. Users can configure
    the items on either side of the equation, but cannot change the equation
    structure or operators.

    The layout is ideal for scenarios where specific inputs need to be summed
    or combined to produce a result, and is commonly used in educational,
    financial, or analytical presentations. Customization options are available
    for background color, font colors, and font sizes for each component,
    allowing for visual adaptation to fit specific themes or presentation needs.
    """
    @staticmethod
    def build(level_1_items: typing.List[str], background_color: Color = ..., level_1_font_color: Color = ..., level_1_font_size=...) -> LayoutElement:
        """
        Construct a vertical equation layout displaying a fixed format equation: "A + B + C ... = D".

        This method arranges items horizontally in a predetermined equation
        structure, where each item in `level_1_items` is displayed sequentially
        as terms (A, B, C, etc.) on the left side of a "+" operation, culminating
        in an "=" operation leading to the final result. The "+" and "=" operators
        are fixed and cannot be modified. Customization options for background
        color, font color, and font size allow the equation's appearance to be
        tailored as needed.

        :param level_1_items:       A list of strings representing the items to be  included in the equation, where each item will represent a term of the equation.
        :param background_color:    The background color for the layout. Defaults to X11Color.PRUSSIAN_BLUE.
        :param level_1_font_color:  The font color for the equation terms. Defaults to X11Color.WHITE.
        :param level_1_font_size:   The font size for the equation terms. Defaults to 12.
        :return:                    A LayoutElement representing the horizontal equation layout, ready for rendering with a fixed structure showing "A + B + C ... = D".
        """
        ...
    


