"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.color.color import Color
from borb.pdf.layout_element.layout_element import LayoutElement

"""
Represents a vertical process layout that visually organizes a series of items as blocks connected by arrows, illustrating the flow of a process.

This class is designed to create a structured representation of a process,
where each item in the process is displayed as a block. Arrows connect
these blocks, indicating the sequence and direction of the process flow.
This layout is particularly useful for visualizing workflows, project
steps, or any sequential operations.
"""
class VerticalProcess:
    """
    Represents a vertical process layout that visually organizes a series of items as blocks connected by arrows, illustrating the flow of a process.

    This class is designed to create a structured representation of a process,
    where each item in the process is displayed as a block. Arrows connect
    these blocks, indicating the sequence and direction of the process flow.
    This layout is particularly useful for visualizing workflows, project
    steps, or any sequential operations.
    """
    @staticmethod
    def build(level_1_items: typing.List[str], background_color: Color = ..., level_1_font_color: Color = ..., level_1_font_size=...) -> LayoutElement:
        """
        Construct a vertical process layout with items represented as blocks connected by arrows.

        This static method creates a visual representation of a series of items
        in a process, where each item (level 1) is displayed as a block.
        The blocks are connected by arrows to illustrate the flow of the process.
        Users can customize the background color, font color, and font size
        for the block labels, allowing for a tailored appearance.

        :params: level_1_items: A list of strings representing the items in the process.
        :params: background_color: The background color for the layout. Defaults to X11Color.PRUSSIAN_BLUE.
        :params: level_1_font_color: The font color for the block labels. Defaults to X11Color.WHITE.
        :params: level_1_font_size: The font size for the block labels. Defaults to 12.
        :returns: A LayoutElement representing the constructed vertical process layout, suitable for rendering.
        """
        ...
    


