"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.color.color import Color
from borb.pdf.document_layout.document_layout import DocumentLayout

"""
Represent a resume in A4 portrait format.

The `A4PortraitResume` class enables users to create and customize a professional resume in A4 portrait layout.
It provides methods for adding personal information, work experience, education, skills, and other relevant sections
to the resume.
"""
class A4PortraitResume(DocumentLayout):
    """
    Represent a resume in A4 portrait format.

    The `A4PortraitResume` class enables users to create and customize a professional resume in A4 portrait layout.
    It provides methods for adding personal information, work experience, education, skills, and other relevant sections
    to the resume.
    """
    __DARK_GRAY: Color = ...
    __WHITE: Color = ...
    __YELLOW_MUNSELL: Color = ...
    def __init__(self) -> None:
        """
        Initialize an A4PortraitResume object, a specialized subclass of A4Portrait for creating resumes.

        This constructor sets up a default A4 portrait-oriented document with pre-defined formatting
        and layout styles suited for creating professional resumes. No parameters are required.
        """
        ...
    
    def append_honors_or_award(self, honor_or_award: str) -> A4PortraitResume:
        """
        Add an honor or award to the resume.

        This method appends a given honor or award to the honors and awards
        section of the resume.

        :param honor_or_award: A string describing the honor or award to add.
        :return: The updated A4PortraitResume instance.
        """
        ...
    
    def append_language_and_proficiency(self, language: str, proficiency_on_a_scale_of_1_to_5: int) -> A4PortraitResume:
        """
        Add a language and its proficiency level to the resume.

        This method appends a language and the user's proficiency level
        (on a scale of 1 to 5) to the languages and proficiency section
        of the resume.

        :param language: The language to add.
        :param proficiency_on_a_scale_of_1_to_5: The proficiency level of the language on a scale from 1 (basic) to 5 (fluent).
        :return: The updated A4PortraitResume instance.
        """
        ...
    
    def append_skill(self, skill: str) -> A4PortraitResume:
        """
        Add a skill to the resume.

        This method appends a skill to the skills section of the resume.

        :param skill: A string describing the skill to add.
        :return: The updated A4PortraitResume instance.
        """
        ...
    
    def append_work_experience(self, company: str, description: str, from_date: str, tags: typing.List[str], to_date: str) -> A4PortraitResume:
        """
        Add a work experience entry to the resume.

        This method appends a work experience entry to the work experience
        section of the resume. Each entry includes the company name, duration,
        description, and associated tags.

        :param company: The name of the company where the experience was gained.
        :param description: A brief description of the role or responsibilities.
        :param from_date: The starting date of the experience (e.g., "Jan 2020").
        :param tags: A list of tags summarizing key skills or technologies used.
        :param to_date: The ending date of the experience (e.g., "Dec 2022").
        :return: The updated A4PortraitResume instance.
        """
        ...
    
    def save(self, path: str) -> A4PortraitResume:
        """
        Save the resume to a specified file path.

        This method writes the current resume document to the given file path.
        The document will be saved in the PDF format. If the file already exists,
        it may be overwritten.

        :param path:    The file path where the resume will be saved.
        :return:        Self, allowing for method chaining.
        """
        ...
    
    def set_about_me(self, about_me: str) -> A4PortraitResume:
        """
        Set the candidate's 'About Me' section on the CV.

        Adds a brief personal summary to introduce the candidate's background, skills, and interests.

        :param about_me: Personal summary text describing the candidate.
        :return: Returns the A4PortraitResume instance for method chaining.
        """
        ...
    
    def set_email(self, email: str) -> A4PortraitResume:
        """
        Set the candidate's email address on the CV.

        Adds the specified email address to the resume's contact details section.

        :param email: Email address of the candidate.
        :return: Returns the A4PortraitResume instance for method chaining.
        """
        ...
    
    def set_linkedin(self, linkedin_url: str) -> A4PortraitResume:
        """
        Set the candidate's LinkedIn profile URL on the CV.

        Adds the specified LinkedIn URL to the resume, displaying it within the
        candidate's contact details section for easy access.

        :param linkedin_url: URL to the candidate’s LinkedIn profile.
        :return: Returns the A4PortraitResume instance for method chaining.
        """
        ...
    
    def set_location(self, location: str) -> A4PortraitResume:
        """
        Set the candidate's location on the CV.

        Adds the specified location (e.g., city, state, or country) to the resume,
        displaying it as part of the candidate’s contact information.

        :param location: Candidate’s location information.
        :return: Returns the A4PortraitResume instance for method chaining.
        """
        ...
    
    def set_name(self, name: str) -> A4PortraitResume:
        """
        Set the candidate's name on the CV.

        Adds the specified name to the resume, displaying it prominently at the top
        as part of the candidate's main information.

        :param name: Full name of the candidate.
        :return: Returns the A4PortraitResume instance for method chaining.
        """
        ...
    
    def set_phone_nr(self, phone_nr: str) -> A4PortraitResume:
        """
        Set the phone number on the CV.

        Adds the specified phone number to the resume, displaying it as part of the contact
        information in the document.

        :param phone_nr: Phone number to include in the resume.
        :return: Returns the A4PortraitResume instance for method chaining.
        """
        ...
    
    def set_picture(self, picture_url: str) -> A4PortraitResume:
        """
        Set the profile picture for the resume.

        This method sets the URL of the profile picture to be included in the resume.

        :param picture_url: The URL of the profile picture.
        :return: The updated A4PortraitResume instance.
        """
        ...
    
    def set_twitter(self, twitter: str) -> A4PortraitResume:
        """
        Set the Twitter handle on the CV.

        Adds the provided Twitter handle to the resume, allowing it to display alongside other
        contact information in the document. The Twitter handle is typically formatted as `@handle`.

        :param twitter: Twitter handle to include in the resume.
        :return: Returns the A4PortraitResume instance for method chaining.
        """
        ...
    


