"""
This type stub file was generated by pyright.
"""

import pathlib
import typing
from borb.pdf.color.color import Color
from borb.pdf.document_layout.document_layout import DocumentLayout
from borb.pdf.layout_element.image.avatar import Avatar

"""
Represents the highest level of abstraction in the PDF library.

The `Slideshow` class allows users to create a PDF document resembling a
slideshow without concerning themselves with formatting details. Users are
only required to provide content, while the class handles layout and
presentation.

It includes methods for easily creating slides tailored to specific content
types, such as slides featuring charts, text, tables, and more.
"""
class Slideshow(DocumentLayout):
    """
    Represents the highest level of abstraction in the PDF library.

    The `Slideshow` class allows users to create a PDF document resembling a
    slideshow without concerning themselves with formatting details. Users are
    only required to provide content, while the class handles layout and
    presentation.

    It includes methods for easily creating slides tailored to specific content
    types, such as slides featuring charts, text, tables, and more.
    """
    __DARK_GRAY: Color = ...
    __LIGHT_GRAY: Color = ...
    __VERY_DARK_GRAY: Color = ...
    __YELLOW_MUNSELL: Color = ...
    __SECTION_TITLE_IMAGES: typing.List[str] = ...
    def __init__(self) -> None:
        """
        Initialize the Slideshow object with a specified theme for content generation.

        The `Slideshow` class provides a high-level interface for creating presentations
        by allowing users to focus solely on the content without needing to manage style or layout options.
        This constructor initializes the slideshow with a default document structure
        and applies a theme that defines the color scheme for the slides.
        If a custom theme is provided, it overrides the default colors where specified.
        The flexibility of this class makes it easy to generate visually coherent presentations
        while minimizing the complexity involved in layout management.

        """
        ...
    
    def append_avatar(self, background_style_type: Avatar.BackgroundStyleType = ..., clothing_type: Avatar.ClothingType = ..., eye_type: Avatar.EyeType = ..., eyebrow_type: Avatar.EyebrowType = ..., facial_hair_type: Avatar.FacialHairType = ..., glasses_type: Avatar.GlassesType = ..., hair_color_type: Avatar.HairColorType = ..., mouth_type: Avatar.MouthType = ..., shirt_logo_type: Avatar.ShirtLogoType = ..., skin_color_type: Avatar.SkinColorType = ..., top_of_head_type: Avatar.TopOfHeadType = ...) -> Slideshow:
        """
        Add a customizable cartoon avatar to the slideshow.

        This method allows users to insert a cartoon-style avatar into a PDF slideshow.
        The avatar can be personalized through a variety of attributes, including clothing,
        hair color, facial features, and accessories.
        Users can choose from different predefined options for each attribute to represent a unique avatar.
        The avatar can be placed on a background with various styles such as a circle or transparent background.
        After customization, the avatar is added as an element to the slideshow.
        This method returns the slideshow instance to allow for method chaining,
        enabling the user to continue adding other elements.

        :param background_style_type: The style of the avatar's background (e.g., circle, transparent). Defaults to CIRCLE.
        :param clothing_type: The type of clothing the avatar wears (e.g., hoodie, t-shirt). Defaults to HOODIE.
        :param eyebrow_type: The style of the avatar's eyebrows (e.g., default, thick). Defaults to DEFAULT.
        :param eye_type: The style of the avatar's eyes (e.g., default, squint). Defaults to DEFAULT.
        :param facial_hair_type: The type of facial hair (e.g., beard, clean-shaven). Defaults to BEARD_MEDIUM.
        :param glasses_type: The type of glasses worn by the avatar (e.g., prescription, sunglasses). Defaults to PRESCRIPTION_BLACK.
        :param hair_color_type: The color of the avatar's hair (e.g., brown, blond). Defaults to BROWN.
        :param mouth_type: The expression of the avatar's mouth (e.g., smile, frown). Defaults to SMILE.
        :param shirt_logo_type: The logo displayed on the avatar's shirt (e.g., bear, skull). Defaults to BEAR.
        :param skin_color_type: The skin color of the avatar (e.g., light, dark). Defaults to LIGHT.
        :param top_of_head_type: The style of the avatar's hair or headwear (e.g., short hair, hat). Defaults to SHORT_HAIR_SIDES.
        :return: Returns the slideshow instance with the avatar added, allowing for method chaining.
        """
        ...
    
    def append_avatar_and_text(self, text: str, title: str, background_style_type: Avatar.BackgroundStyleType = ..., clothing_type: Avatar.ClothingType = ..., eye_type: Avatar.EyeType = ..., eyebrow_type: Avatar.EyebrowType = ..., facial_hair_type: Avatar.FacialHairType = ..., glasses_type: Avatar.GlassesType = ..., hair_color_type: Avatar.HairColorType = ..., mouth_type: Avatar.MouthType = ..., shirt_logo_type: Avatar.ShirtLogoType = ..., skin_color_type: Avatar.SkinColorType = ..., top_of_head_type: Avatar.TopOfHeadType = ...) -> Slideshow:
        """
        Add a customizable avatar and accompanying text to the slideshow.

        This method creates an avatar with customizable appearance options and places it
        alongside a title and body text in the slideshow. Each attribute parameter allows
        specification of details like facial features, clothing style, and accessories to
        personalize the avatar.

        :param text: The body text to display alongside the avatar.
        :param title: Title text to display above or near the avatar.
        :param background_style_type: Style of the avatar background (e.g., circle, square).
        :param clothing_type: Type of clothing the avatar wears.
        :param eye_type: Style of the avatar’s eyes.
        :param eyebrow_type: Style of the avatar’s eyebrows.
        :param facial_hair_type: Type of facial hair for the avatar.
        :param glasses_type: Style of glasses for the avatar.
        :param hair_color_type: Color of the avatar’s hair.
        :param mouth_type: Style of the avatar’s mouth.
        :param shirt_logo_type: Style of logo on the avatar’s shirt.
        :param skin_color_type: Skin color of the avatar.
        :param top_of_head_type: Hair or head style of the avatar.
        :return: Returns the Slideshow instance for method chaining.
        """
        ...
    
    def append_barchart(self, xs: typing.List[float], ys: typing.List[str], y_label: typing.Optional[str] = ...) -> Slideshow:
        """
        Add a bar chart to the PDF document.

        The `add_barchart` method inserts a bar chart into the document,
        using the provided data values and labels.
        This is useful for visualizing categorical data and comparing different values across categories.

        :param xs:      A list of numerical values representing the heights of the bars in the chart.
        :param ys:      A list of labels corresponding to each bar in the chart.
        :param y_label: A descriptive label for the y-axis of the bar chart.
        :return:        Self, allowing for method chaining
        """
        ...
    
    def append_barchart_and_text(self, text: str, title: str, xs: typing.List[float], ys: typing.List[str], y_label: typing.Optional[str] = ...) -> Slideshow:
        """
        Add a slide with a bar chart, accompanying text, and a title to the PDF document.

        The `add_barchart_and_text` method creates a slide that includes a bar chart, descriptive text, and a title.
        The bar chart is generated from the provided data values and labels,
        while the text can be used to explain or provide context for the chart.

        :param text:    The descriptive text to be displayed alongside the bar chart.
        :param title:   The title text to be prominently displayed at the top of the slide.
        :param xs:      A list of numerical values representing the heights of the bars in the chart.
        :param ys:      A list of labels corresponding to each bar in the chart.
        :param y_label: A descriptive label for the y-axis of the bar chart.
        :return:        Self, allowing for method chaining
        """
        ...
    
    def append_big_number(self, big_number: str) -> Slideshow:
        """
        Add a slide containing a prominently displayed big number.

        This method creates a new slide with a single large number centered on it.
        This is useful for emphasizing a key statistic or figure that needs to capture
        the audience's attention.

        :param big_number:  The number to be displayed on the slide.
        :return:            Self, allowing for method chaining.
        """
        ...
    
    def append_big_number_and_text(self, big_number: str, text: str, title: str) -> Slideshow:
        """
        Add a slide with a large number, accompanying text, and a title to the PDF document.

        The `add_big_number_and_text` method creates a slide that prominently displays a large number,
        which is typically used to highlight key metrics or statistics.
        The slide also includes a block of descriptive text and a title to provide context or explanation for the number.

        :param big_number:  A string representing the large number to be prominently displayed on the slide.
        :param text:        The descriptive text to be displayed below or alongside the big number.
        :param title:       The title text to be prominently displayed at the top of the slide.
        :return:            Self, allowing for method chaining.
        """
        ...
    
    def append_blank(self) -> Slideshow:
        """
        Add a purposefully blank slide to the slideshow.

        This method creates a slide that intentionally contains no content. It
        can be used to signify a transition or a pause in the presentation,
        allowing the audience to focus on the previous content or prepare for
        what comes next.

        :return: Self, allowing for method chaining.
        """
        ...
    
    def append_code_snippet(self, code: str) -> Slideshow:
        """
        Add a slide with a code snippet to the PDF document.

        The `add_code_snippet` method creates a slide that displays a snippet of code.
        This is useful for presentations that include programming examples,
        syntax highlighting, or technical demonstrations.
        The code is presented in a readable, formatted style on the slide.

        :param code:    The code string to be displayed in the code snippet.
        :return:        Self, allowing for method chaining.
        """
        ...
    
    def append_code_snippet_and_text(self, code: str, text: str, title: str) -> Slideshow:
        """
        Add a slide with a code snippet, accompanying text, and a title to the PDF document.

        The `add_code_snippet_and_text` method creates a slide that features
        a snippet of code along with descriptive text and a title.
        This is useful for presenting programming examples or technical content in a clear and organized manner,
        allowing the audience to understand the context of the code being shown.

        :param code:    The code string to be displayed in the code snippet.
        :param text:    The descriptive text to be displayed alongside or below the code snippet.
        :param title:   The title text to be prominently displayed at the top of the slide.
        :return:        Self, allowing for method chaining.
        """
        ...
    
    def append_image(self, url_or_path: typing.Union[str, pathlib.Path]) -> Slideshow:
        """
        Add an image to the slideshow.

        This method allows users to include an image in the current slide.
        The image can be specified either by a URL or a local file path.
        Once added, the image will be included in the slideshow presentation.

        :param url_or_path: The URL or local file path of the image to be added.
        :return:            Self, allowing for method chaining.
        """
        ...
    
    def append_image_and_text(self, path_or_url: typing.Union[pathlib.Path, str], text: str, title: str) -> Slideshow:
        """
        Add a slide that includes an image along with a title and descriptive text.

        This method creates a new slide featuring the specified image, which can be
        provided as a file path or a URL. The slide will also display a title and
        accompanying text, allowing for the presentation of visual content alongside
        relevant information.

        :param path_or_url: The file path or URL of the image to be displayed on the slide.
        :param text:        The descriptive text to accompany the image.
        :param title:       The title associated with the slide.
        :return:            Self, allowing for method chaining.
        """
        ...
    
    def append_line_chart(self, labels: typing.List[str], xs: typing.List[typing.List[float]], ys: typing.List[typing.List[float]], x_label: typing.Optional[str] = ..., y_label: typing.Optional[str] = ...) -> Slideshow:
        """
        Add a line chart to the PDF document.

        The `add_linechart` method inserts a line chart into the document using the provided data series and labels.
        Multiple data series can be included, each with its own label.
        Optional axis labels can also be provided for further clarity.

        :param xs:          A list of lists where each sublist contains x-values (e.g., time or categories) for the corresponding data series.
        :param ys:          A list of lists where each sublist contains y-values (e.g., data points) for the corresponding data series.
        :param labels:      A list of strings representing the labels for each data series.
        :param x_label:     Optional. A label for the x-axis of the line chart.
        :param y_label:     Optional. A label for the y-axis of the line chart.
        :return:            Self, allowing for method chaining
        """
        ...
    
    def append_line_chart_and_text(self, labels: typing.List[str], text: str, title: str, xs: typing.List[typing.List[float]], ys: typing.List[typing.List[float]], x_label: typing.Optional[str] = ..., y_label: typing.Optional[str] = ...) -> Slideshow:
        """
        Add a slide with a line chart, accompanying text, and a title to the PDF document.

        The `add_line_chart_and_text` method creates a slide that includes a line chart with multiple data series,
        a block of descriptive text, and a title.
        The chart is generated using the provided x-values, y-values, and series labels,
        while optional axis labels can be specified to clarify the chart's axes.

        :param text:    The descriptive text to be displayed alongside the line chart.
        :param title:   The title text to be prominently displayed at the top of the slide.
        :param xs:      A list of lists where each sublist contains x-values for the corresponding data series.
        :param ys:      A list of lists where each sublist contains y-values for the corresponding data series.
        :param labels:  A list of strings representing the labels for each data series.
        :param x_label: Optional. A label for the x-axis of the line chart.
        :param y_label: Optional. A label for the y-axis of the line chart.
        :return:        Self, allowing for method chaining
        """
        ...
    
    def append_map_of_europe(self, marked_countries: typing.List[str] = ...) -> Slideshow:
        """
        Add a slide with a map of Europe to the PDF document, with optional highlighted countries.

        The `add_map_of_europe` method creates a slide featuring a map of Europe.
        Optionally, specific countries can be highlighted to emphasize geographic data or focus on certain regions.
        This slide does not include additional text or titles.

        :param marked_countries:    A list of country names (strings) to be highlighted on the map.
                                    Default is an empty list (no countries highlighted).
        :return:                    Self, allowing for method chaining.
        """
        ...
    
    def append_map_of_europe_and_text(self, text: str, title: str, marked_countries: typing.List[str] = ...) -> Slideshow:
        """
        Add a slide with a map of Europe, accompanying text, and a title to the PDF document.

        The `add_map_of_europe_and_text` method creates a slide that features a map of Europe,
        with the option to highlight specific countries.
        The slide also includes descriptive text and a title,
        making it useful for presenting geographic data or emphasizing particular countries in Europe.

        :param text:                The descriptive text to be displayed alongside or below the map.
        :param title:               The title text to be prominently displayed at the top of the slide.
        :param marked_countries:    A list of country names (strings) to be highlighted on the map.
                                    Default is an empty list (no countries highlighted).
        :return:                    Self, allowing for method chaining.
        """
        ...
    
    def append_map_of_the_contiguous_united_states(self, marked_states: typing.List[str] = ...) -> Slideshow:
        """
        Add a slide with a map of the contiguous United States to the PDF document, with optional highlighted states.

        The `add_map_of_the_contiguous_united_states` method creates a slide
        featuring a map of the contiguous United States (excluding Alaska and Hawaii).
        Optionally, specific states can be highlighted to emphasize geographic data or focus on certain regions.
        This slide does not include additional text or titles.

        :param marked_states:   A list of state names (strings) to be highlighted on the map.
                                Default is an empty list (no states highlighted).
        :return:                Self, allowing for method chaining.
        """
        ...
    
    def append_map_of_the_contiguous_united_states_and_text(self, text: str, title: str, marked_states: typing.List[str] = ...) -> Slideshow:
        """
        Add a slide with a map of the contiguous United States, accompanying text, and a title to the PDF document.

        The `add_map_of_the_contiguous_united_states_and_text` method creates a slide
        that features a map of the contiguous United States (excluding Alaska and Hawaii),
        with the option to highlight specific states.
        The slide also includes descriptive text and a title,
        making it useful for presenting geographic data or focusing on specific states.

        :param text:            The descriptive text to be displayed alongside or below the map.
        :param title:           The title text to be prominently displayed at the top of the slide.
        :param marked_states:   A list of state names (strings) to be highlighted on the map.
                                Default is an empty list (no states highlighted).
        :return:                Self, allowing for method chaining.
        """
        ...
    
    def append_map_of_the_united_states(self, marked_states: typing.List[str] = ...) -> Slideshow:
        """
        Add a slide with a map of the United States to the PDF document, with optional highlighted states.

        The `add_map_of_the_united_states` method creates a slide featuring a map of the United States.
        Optionally, specific states can be highlighted to emphasize geographic data or focus on certain regions.
        This slide does not include additional text or titles.

        :param marked_states:   A list of state names (strings) to be highlighted on the map.
                                Default is an empty list (no states highlighted).
        :return:                Self, allowing for method chaining.
        """
        ...
    
    def append_map_of_the_united_states_and_text(self, text: str, title: str, marked_states: typing.List[str] = ...) -> Slideshow:
        """
        Add a slide with a map of the United States, accompanying text, and a title to the PDF document.

        The `add_map_of_the_united_states_and_text` method creates a slide that features a map of the United States,
        with the option to highlight specific states.
        Descriptive text and a title are also included on the slide.
        This is useful for presenting geographic data or visualizing information by state.

        :param text:            The descriptive text to be displayed alongside or below the map.
        :param title:           The title text to be prominently displayed at the top of the slide.
        :param marked_states:   A list of state names (strings) to be highlighted on the map.
                                Default is an empty list (no states highlighted).
        :return:                Self, allowing for method chaining.
        """
        ...
    
    def append_map_of_the_world(self, marked_countries: typing.List[str] = ...) -> Slideshow:
        """
        Add a slide with a world map to the PDF document, with optional highlighted countries.

        The `add_map_of_the_world` method creates a slide featuring a world map.
        Optionally, specific countries can be highlighted to emphasize geographic data or focus on certain regions.
        This slide does not include additional text or titles.

        :param marked_countries:    A list of country names (strings) to be highlighted on the world map.
                                    Default is an empty list (no countries highlighted).
        :return:                    Self, allowing for method chaining.
        """
        ...
    
    def append_map_of_the_world_and_text(self, text: str, title: str, marked_countries: typing.List[str] = ...) -> Slideshow:
        """
        Add a slide with a world map, accompanying text, and a title to the PDF document.

        The `add_map_of_the_world_and_text` method creates a slide that features a world map,
        with optional highlighted countries.
        Descriptive text and a title are also included on the slide.
        This method is useful for visually presenting geographic data, highlighting specific countries,
        or adding context with textual explanation.

        :param text:                The descriptive text to be displayed alongside or below the world map.
        :param title:               The title text to be prominently displayed at the top of the slide.
        :param marked_countries:    A list of country names (strings) to be highlighted on the world map.
                                    Default is an empty list (no countries highlighted).
        :return:                    Self, allowing for method chaining.
        """
        ...
    
    def append_ordered_list(self, list_data: typing.List[str]) -> Slideshow:
        """
        Add a slide containing an ordered list based on the provided list data.

        This method creates a new slide that presents a sequence of items in a
        structured ordered list format. The list is generated from the provided
        list of strings, where each string represents an item in the list.
        This format helps to clearly convey a ranked or sequential order of information.

        :param list_data:   A list of strings containing the items to be displayed
                            in the ordered list.
        :return:            Self, allowing for method chaining.
        """
        ...
    
    def append_ordered_list_and_text(self, list_data: typing.List[str], text: str, title: str) -> Slideshow:
        """
        Add a slide with an ordered list, accompanying text, and a title to the PDF document.

        The `add_ordered_list_and_text` method creates a slide that includes an ordered list (numbered list)
        based on the provided list of items.
        It also features descriptive text and a title at the top of the slide.
        This method is ideal for presenting a sequence of steps or ranked items along with explanatory text.

        :param list_data:   A list of strings representing the items in the ordered (numbered) list.
        :param text:        The descriptive text to be displayed alongside or below the ordered list.
        :param title:       The title text to be prominently displayed at the top of the slide.
        :return:            Self, allowing for method chaining
        """
        ...
    
    def append_pie_chart(self, xs: typing.List[float], ys: typing.List[str], y_label: typing.Optional[str] = ...) -> Slideshow:
        """
        Add a pie chart to the PDF document.

        The `add_pie_chart` method allows users to easily incorporate a pie chart into the PDF.
        Users provide the data values and corresponding labels, and the method takes care of
        generating the chart in the appropriate format and layout.

        :param xs:      A list of numerical values representing the segments of the pie chart.
        :param ys:      A list of labels corresponding to each segment in the pie chart.
        :param y_label: A descriptive label for the pie chart, which will be displayed prominently.
        :return:        Self, allowing for method chaining.
        """
        ...
    
    def append_pie_chart_and_text(self, text: str, title: str, xs: typing.List[float], ys: typing.List[str], y_label: typing.Optional[str] = ...) -> Slideshow:
        """
        Add a slide with a pie chart, accompanying text, and a title to the PDF document.

        The `add_pie_chart_and_text` method creates a slide featuring a pie chart along with a block of descriptive text.
        The pie chart is generated from the provided data values and labels,
        and the text can be used to explain or elaborate on the chart.

        :param text:    The descriptive text to be displayed alongside the pie chart.
        :param title:   The title text to be prominently displayed at the top of the slide.
        :param xs:      A list of numerical values representing the segments of the pie chart.
        :param ys:      A list of labels corresponding to each segment in the pie chart.
        :param y_label: A descriptive label for the pie chart, which will be displayed on the slide.
        :return:        Self, allowing for method chaining.
        """
        ...
    
    def append_qr_code(self, url: str) -> Slideshow:
        """
        Add a slide containing a QR code linked to a specified URL.

        This method generates a QR code that encodes the provided URL and places it
        on a new slide. This allows the audience to easily scan the QR code with their
        devices to access the linked content.

        :param url: The URL to be encoded in the QR code.
        :return:    Self, allowing for method chaining.
        """
        ...
    
    def append_qr_code_and_text(self, text: str, title: str, url: str) -> Slideshow:
        """
        Add a slide containing a QR code alongside descriptive text and a title.

        This method creates a new slide that features a QR code generated from the
        provided URL, along with the specified title and text. This is useful for
        presentations where you want to direct the audience to a web resource or
        provide additional information while maintaining an engaging visual layout.

        :param text:    A string containing the descriptive text to be displayed on the slide.
        :param title:   A string representing the title to be displayed on the slide.
        :param url:     A string representing the URL that the QR code will link to.
        :return:        Self, allowing for method chaining.
        """
        ...
    
    def append_quote(self, author: str, quote: str) -> Slideshow:
        """
        Add a slide containing a quote attributed to a specified author.

        This method creates a new slide that features the provided quote prominently,
        along with the name of the author. This is useful for highlighting impactful
        statements or insights within the presentation.

        :param author:  The name of the author of the quote.
        :param quote:   The quote to be displayed on the slide.
        :return:        Self, allowing for method chaining.
        """
        ...
    
    def append_quote_and_text(self, author: str, quote: str, text: str, title: str) -> Slideshow:
        """
        Add a slide with a quote, the author's name, accompanying text, and a title to the PDF document.

        The `add_quote_and_text` method creates a slide that features a prominently displayed quote, the author's name,
        and additional descriptive text.
        The title is displayed at the top, while the text serves to elaborate on or contextualize the quote.

        :param author:  The name of the author of the quote, displayed below the quote.
        :param text:    The descriptive text to be displayed alongside or below the quote.
        :param title:   The title text to be prominently displayed at the top of the slide.
        :param quote:   The quote to be displayed prominently on the slide.
        :return:        Self, allowing for method chaining
        """
        ...
    
    def append_section_title(self, subtitle: str, title: str) -> Slideshow:
        """
        Add a section title and subtitle to the PDF document.

        The `add_section_title` method inserts a title and an optional subtitle
        to mark the beginning of a new section in the document.
        This is useful for structuring content by clearly defining sections within the slideshow.

        :param subtitle:    The subtitle text to be displayed below the section title. Can be left empty for no subtitle.
        :param title:       The main section title to be prominently displayed.
        :return:            Self, allowing for method chaining.
        """
        ...
    
    def append_single_column_of_text(self, text: str, title: str) -> Slideshow:
        """
        Add a slide with a single column of text and a title to the PDF document.

        The `add_single_column_of_text` method creates a slide that features a title
        at the top and a single column of text. This is useful for presenting blocks of text,
        such as descriptions, explanations, or bullet points, in a clear and concise manner.

        :param text:    The body of text to be displayed in a single column on the slide.
        :param title:   The title text to be prominently displayed at the top of the slide.
        :return:        Self, allowing for method chaining.
        """
        ...
    
    def append_table(self, tabular_data: typing.List[typing.List[typing.Any]]) -> Slideshow:
        """
        Add a slide containing a table based on the provided tabular data.

        This method creates a new slide that presents data in a structured table format.
        The table is generated from the given list of lists, where each inner list
        represents a row of data. This allows for clear organization and presentation
        of various types of information.

        :param tabular_data:    A list of lists containing the data for the table,
                                where each inner list corresponds to a row.
        :return:                Self, allowing for method chaining.
        """
        ...
    
    def append_table_and_text(self, tabular_data: typing.List[typing.List[str]], text: str, title: str) -> Slideshow:
        """
        Add a slide with a table, accompanying text, and a title to the PDF document.

        The `add_table_and_text` method creates a slide that displays a table of data along with
        a block of descriptive text and a title.
        The table is constructed from the provided 2D list of strings,
        where each sublist represents a row in the table.
        This method is ideal for presenting structured data along with explanatory text.

        :param tabular_data:    A 2D list of strings representing the table's content. Each sublist corresponds to a row of the table.
        :param text:            The descriptive text to be displayed alongside or below the table.
        :param title:           The title text to be prominently displayed at the top of the slide.
        :return:                Self, allowing for method chaining
        """
        ...
    
    def append_title(self, subtitle: str, title: str) -> Slideshow:
        """
        Add a title and subtitle to the PDF document.

        The `add_title` method allows the user to insert a title and
        a subtitle at a predefined position in the document.
        This is typically used for the main slide or opening page in a slideshow-style PDF.

        :param subtitle:    The subtitle text to be displayed below the title. Can be left empty for no subtitle.
        :param title:       The main title text to be prominently displayed.
        :return:            Self, allowing for method chaining.
        """
        ...
    
    def append_two_columns_of_text(self, text_left: str, text_right: str, title: str) -> Slideshow:
        """
        Add a slide with two columns of text and a title to the PDF document.

        The `add_two_columns_of_text` method creates a slide that displays text in two columns,
        allowing for a side-by-side comparison or presentation of related content.
        A title is displayed at the top of the slide, while the left and right columns contain the provided text.

        :param title:       The title text to be prominently displayed at the top of the slide.
        :param text_right:  The text to be displayed in the right column.
        :param text_left:   The text to be displayed in the left column.
        :return:            Self, allowing for method chaining
        """
        ...
    
    def append_unordered_list(self, list_data: typing.List[str]) -> Slideshow:
        """
        Add a slide containing an unordered list based on the provided list data.

        This method creates a new slide that presents a collection of items in a
        structured unordered list format. The list is generated from the provided
        list of strings, where each string represents an item in the list.
        This format is useful for displaying information without implying a specific
        order or ranking.

        :param list_data:   A list of strings containing the items to be displayed
                            in the unordered list.
        :return:            Self, allowing for method chaining.
        """
        ...
    
    def append_unordered_list_and_text(self, list_data: typing.List[str], text: str, title: str) -> Slideshow:
        """
        Add a slide with an unordered list, accompanying text, and a title to the PDF document.

        The `add_unordered_list_and_text` method creates a slide that includes an unordered list
        generated from the provided list of items.
        It also features descriptive text and a title displayed at the top of the slide.
        This method is useful for presenting bullet points along with explanatory text.

        :param list_data:   A list of strings representing the items in the unordered list.
        :param text:        The descriptive text to be displayed alongside or below the unordered list.
        :param title:       The title text to be prominently displayed at the top of the slide.
        :return:            Self, allowing for method chaining
        """
        ...
    
    def save(self, path: str) -> Slideshow:
        """
        Save the slideshow to a specified file path.

        This method writes the current slideshow document to the given file path.
        The document will be saved in the PDF format. If the file already exists,
        it may be overwritten.

        :param path:    The file path where the slideshow will be saved.
        :return:        Self, allowing for method chaining.
        """
        ...
    


