"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.color.color import Color
from borb.pdf.layout_element.image.image import Image
from borb.pdf.layout_element.layout_element import LayoutElement

"""
A class that uses matplotlib and LaTeX to render mathematical equations as images.

The `Equation` class extends the `Image` class and provides functionality to
generate a high-quality image of a mathematical equation. It utilizes LaTeX for
typesetting the equation and matplotlib for rendering the LaTeX code as an image.
"""
class Equation(Image):
    """
    A class that uses matplotlib and LaTeX to render mathematical equations as images.

    The `Equation` class extends the `Image` class and provides functionality to
    generate a high-quality image of a mathematical equation. It utilizes LaTeX for
    typesetting the equation and matplotlib for rendering the LaTeX code as an image.
    """
    def __init__(self, latex_syntax: str, background_color: typing.Optional[Color] = ..., border_color: typing.Optional[Color] = ..., border_dash_pattern: typing.List[int] = ..., border_dash_phase: int = ..., border_width_bottom: int = ..., border_width_left: int = ..., border_width_right: int = ..., border_width_top: int = ..., font_color: Color = ..., font_size: int = ..., horizontal_alignment: LayoutElement.HorizontalAlignment = ..., margin_bottom: int = ..., margin_left: int = ..., margin_right: int = ..., margin_top: int = ..., padding_bottom: int = ..., padding_left: int = ..., padding_right: int = ..., padding_top: int = ..., size: typing.Optional[typing.Tuple[int, int]] = ..., vertical_alignment: LayoutElement.VerticalAlignment = ...) -> None:
        """
        Initialize an Equation object to render a LaTeX mathematical equation as an image.

        The `Equation` class uses LaTeX syntax to render mathematical equations into an image.
        The image can be customized with various layout properties such as background color, borders, padding, margins, font styles, and alignment.

        :param latex_syntax:            A LaTeX string representing the mathematical equation to render.
        :param background_color:        Optional color for the background of the image. Default is None.
        :param border_color:            Optional color for the border surrounding the image. Default is None.
        :param border_dash_pattern:     A list defining the dash pattern for the border. Default is an empty list (solid border).
        :param border_dash_phase:       The phase offset for the dash pattern. Default is 0.
        :param border_width_bottom:     Width of the border at the bottom of the image. Default is 0 (no border).
        :param border_width_left:       Width of the border on the left side of the image. Default is 0 (no border).
        :param border_width_right:      Width of the border on the right side of the image. Default is 0 (no border).
        :param border_width_top:        Width of the border at the top of the image. Default is 0 (no border).
        :param font_color:              Color of the text (equation). Default is black (X11Color.BLACK).
        :param font_size:               Size of the font used to render the equation. Default is 12.
        :param horizontal_alignment:    Horizontal alignment of the equation within the image. Default is `LEFT`.
        :param margin_bottom:           Bottom margin for spacing around the image. Default is 0.
        :param margin_left:             Left margin for spacing around the image. Default is 0.
        :param margin_right:            Right margin for spacing around the image. Default is 0.
        :param margin_top:              Top margin for spacing around the image. Default is 0.
        :param padding_bottom:          Padding at the bottom of the image. Default is 0.
        :param padding_left:            Padding on the left side of the image. Default is 0.
        :param padding_right:           Padding on the right side of the image. Default is 0.
        :param padding_top:             Padding at the top of the image. Default is 0.
        :param size:                    Optional tuple specifying the dimensions of the image as (width, height). Default is None, which automatically adjusts the size based on content.
        :param vertical_alignment:      Vertical alignment of the equation within the image. Default is `TOP`.
        """
        ...
    


