"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.color.color import Color
from borb.pdf.layout_element.image.image import Image
from borb.pdf.layout_element.layout_element import LayoutElement

"""
Represents a screenshot that can be inserted into a PDF document.

The `Screenshot` class allows users to capture and insert a screenshot into a PDF. It inherits
from the `Image` class, which provides core functionality for handling images in PDF layouts.
The screenshot can be captured directly from the user's screen and then processed like any
other image object.
"""
class Screenshot(Image):
    """
    Represents a screenshot that can be inserted into a PDF document.

    The `Screenshot` class allows users to capture and insert a screenshot into a PDF. It inherits
    from the `Image` class, which provides core functionality for handling images in PDF layouts.
    The screenshot can be captured directly from the user's screen and then processed like any
    other image object.
    """
    def __init__(self, all_screens: bool = ..., background_color: typing.Optional[Color] = ..., border_color: typing.Optional[Color] = ..., border_dash_pattern: typing.List[int] = ..., border_dash_phase: int = ..., border_width_bottom: int = ..., border_width_left: int = ..., border_width_right: int = ..., border_width_top: int = ..., bounding_box: typing.Optional[typing.Tuple[int, int, int, int]] = ..., horizontal_alignment: LayoutElement.HorizontalAlignment = ..., include_layered_windows: bool = ..., margin_bottom: int = ..., margin_left: int = ..., margin_right: int = ..., margin_top: int = ..., padding_bottom: int = ..., padding_left: int = ..., padding_right: int = ..., padding_top: int = ..., size: typing.Optional[typing.Tuple[int, int]] = ..., vertical_alignment: LayoutElement.VerticalAlignment = ..., xdisplay: typing.Optional[str] = ...) -> None:
        """
        Initialize a Screenshot object.

        The `Screenshot` class is designed to capture screenshots with customizable options,
        including the ability to capture all screens, specify background and border colors,
        and define the size and alignment of the screenshot.

        :param all_screens:             If True, capture screenshots from all connected screens. Defaults to False.
        :param background_color:        The background color of the screenshot. Defaults to None.
        :param border_color:            The color of the border around the screenshot. Defaults to None.
        :param border_dash_pattern:     A list defining the dash pattern for the border. Defaults to an empty list.
        :param border_dash_phase:       The phase of the dash pattern. Defaults to 0.
        :param border_width_bottom:     Width of the bottom border in pixels. Defaults to 0.
        :param border_width_left:       Width of the left border in pixels. Defaults to 0.
        :param border_width_right:      Width of the right border in pixels. Defaults to 0.
        :param border_width_top:        Width of the top border in pixels. Defaults to 0.
        :param bounding_box:            A tuple defining the bounding box of the screenshot in the form (x1, y1, x2, y2). Defaults to None.
        :param horizontal_alignment:    Horizontal alignment of the screenshot. Defaults to LayoutElement.HorizontalAlignment.LEFT.
        :param include_layered_windows: If True, include layered (translucent) windows in the screenshot. Defaults to False.
        :param margin_bottom:           Bottom margin in pixels. Defaults to 0.
        :param margin_left:             Left margin in pixels. Defaults to 0.
        :param margin_right:            Right margin in pixels. Defaults to 0.
        :param margin_top:              Top margin in pixels. Defaults to 0.
        :param padding_bottom:          Bottom padding in pixels. Defaults to 0.
        :param padding_left:            Left padding in pixels. Defaults to 0.
        :param padding_right:           Right padding in pixels. Defaults to 0.
        :param padding_top:             Top padding in pixels. Defaults to 0.
        :param size:                    Desired size of the screenshot in points (width, height). Defaults to None.
        :param vertical_alignment:      Vertical alignment of the screenshot. Defaults to LayoutElement.VerticalAlignment.TOP.
        :param xdisplay:                The X display string to connect to. Defaults to None.
        """
        ...
    


