"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.color.color import Color
from borb.pdf.layout_element.image.image import Image
from borb.pdf.layout_element.layout_element import LayoutElement

"""
Represents an image retrieved from the Unsplash API, which can be inserted into a PDF document.

The `Unsplash` class allows users to provide search keywords to find a relevant image from the
Unsplash image database. This class interacts with the Unsplash API, retrieves the image, and
embeds it into a PDF document, inheriting functionality from the `Image` class.
"""
class Unsplash(Image):
    """
    Represents an Image retrieved from the Unsplash API, which can be inserted into a PDF document.

    The `Unsplash` class allows users to provide search keywords to find a relevant image from the
    Unsplash image database. This class interacts with the Unsplash API, retrieves the image, and
    embeds it into a PDF document, inheriting functionality from the `Image` class.
    """
    def __init__(self, keywords: typing.List[str], background_color: typing.Optional[Color] = ..., border_color: typing.Optional[Color] = ..., border_dash_pattern: typing.List[int] = ..., border_dash_phase: int = ..., border_width_bottom: int = ..., border_width_left: int = ..., border_width_right: int = ..., border_width_top: int = ..., horizontal_alignment: LayoutElement.HorizontalAlignment = ..., margin_bottom: int = ..., margin_left: int = ..., margin_right: int = ..., margin_top: int = ..., padding_bottom: int = ..., padding_left: int = ..., padding_right: int = ..., padding_top: int = ..., size: typing.Optional[typing.Tuple[int, int]] = ..., vertical_alignment: LayoutElement.VerticalAlignment = ...) -> None:
        """
        Initialize the UnsplashAPI object to retrieve images based on specified keywords.

        The `UnsplashAPI` class interacts with the Unsplash API to fetch images that match the given keywords.
        This constructor sets up the necessary attributes for image retrieval and display, including the keywords,
        optional background and border colors, layout settings, and image dimensions.
        These attributes determine how the images are displayed in the application
        and allow for customization of the visual presentation.

        :param keywords:                A list of keywords used to search for relevant images from the Unsplash API.
        :param background_color:        Optional color for the background of the image. Default is None.
        :param border_color:            Optional color for the border surrounding the image. Default is None.
        :param border_dash_pattern:     A list defining the dash pattern for the border. Default is an empty list.
        :param border_dash_phase:       The phase offset for the dash pattern. Default is 0.
        :param border_width_bottom:     Width of the border at the bottom of the image. Default is 0.
        :param border_width_left:       Width of the border on the left side of the image. Default is 0.
        :param border_width_right:      Width of the border on the right side of the image. Default is 0.
        :param border_width_top:        Width of the border at the top of the image. Default is 0.
        :param horizontal_alignment:    Alignment of the image horizontally within its layout. Default is LayoutElement.HorizontalAlignment.LEFT.
        :param margin_bottom:           Bottom margin for spacing around the image. Default is 0.
        :param margin_left:             Left margin for spacing around the image. Default is 0.
        :param margin_right:            Right margin for spacing around the image. Default is 0.
        :param margin_top:              Top margin for spacing around the image. Default is 0.
        :param padding_bottom:          Padding at the bottom of the image. Default is 0.
        :param padding_left:            Padding on the left side of the image. Default is 0.
        :param padding_right:           Padding on the right side of the image. Default is 0.
        :param padding_top:             Padding at the top of the image. Default is 0.
        :param size:                    Optional tuple specifying the dimensions of the image as (width, height). Default is None.
        :param vertical_alignment:      Alignment of the image vertically within its layout. Default is LayoutElement.VerticalAlignment.TOP.
        """
        ...
    


