"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.color.color import Color
from borb.pdf.layout_element.image.image import Image
from borb.pdf.layout_element.layout_element import LayoutElement
from borb.pdf.page import Page

"""
Represents a watermark to be applied to PDF documents, inheriting from the Image class.

This class is designed to handle the addition of watermarks (typically semi-transparent images or text) to PDF files.
It extends the functionality of the `Image` class, allowing for customization of watermark properties such as opacity,
size, and position.
"""
class Watermark(Image):
    """
    Represents a watermark to be applied to PDF documents, inheriting from the Image class.

    This class is designed to handle the addition of watermarks (typically semi-transparent images or text) to PDF files.
    It extends the functionality of the `Image` class, allowing for customization of watermark properties such as opacity,
    size, and position.
    """
    def __init__(self, text: str, angle_in_degrees: int = ..., background_color: typing.Optional[Color] = ..., border_color: typing.Optional[Color] = ..., border_dash_pattern: typing.List[int] = ..., border_dash_phase: int = ..., border_width_bottom: int = ..., border_width_left: int = ..., border_width_right: int = ..., border_width_top: int = ..., font_color: Color = ..., font_size: int = ..., horizontal_alignment: LayoutElement.HorizontalAlignment = ..., margin_bottom: int = ..., margin_left: int = ..., margin_right: int = ..., margin_top: int = ..., padding_bottom: int = ..., padding_left: int = ..., padding_right: int = ..., padding_top: int = ..., transparency: float = ..., vertical_alignment: LayoutElement.VerticalAlignment = ...) -> None:
        """
        Initialize a full-page watermark to be applied on the PDF.

        This constructor sets up the watermark text, its appearance, and its positioning
        across the entire page. You can customize the angle, font size, colors, margins,
        padding, and transparency to achieve the desired visual effect. The watermark
        will overlay the content of the PDF, making it suitable for branding or marking
        documents as confidential.

        :param text:                   The text to display as the watermark.
        :param angle_in_degrees:      The angle at which the watermark text is displayed (default is 45).
        :param background_color:       Optional background color for the watermark.
        :param border_color:           Optional border color for the watermark.
        :param border_dash_pattern:    Dash pattern used for the border lines of the watermark.
        :param border_dash_phase:      Phase offset for the dash pattern in the borders.
        :param border_width_bottom:    Width of the bottom border of the watermark.
        :param border_width_left:      Width of the left border of the watermark.
        :param border_width_right:     Width of the right border of the watermark.
        :param border_width_top:       Width of the top border of the watermark.
        :param font_color:             Color of the watermark text (default is RED).
        :param font_size:              Size of the watermark text (default is 24).
        :param horizontal_alignment:    Horizontal alignment of the watermark (default is LEFT).
        :param margin_bottom:          Space between the watermark and the element below it.
        :param margin_left:            Space between the watermark and the left page margin.
        :param margin_right:           Space between the watermark and the right page margin.
        :param margin_top:             Space between the watermark and the element above it.
        :param padding_bottom:         Padding inside the watermark at the bottom.
        :param padding_left:           Padding inside the watermark on the left side.
        :param padding_right:          Padding inside the watermark on the right side.
        :param padding_top:            Padding inside the watermark at the top.
        :param transparency:           Transparency level of the watermark (default is 0.6).
        :param vertical_alignment:      Vertical alignment of the watermark (default is TOP).
        """
        ...
    
    def get_size(self, available_space: typing.Tuple[int, int]) -> typing.Tuple[int, int]:
        """
        Calculate and return the size of the layout element based on available space.

        This function uses the available space to compute the size (width, height)
        of the layout element in points.

        :param available_space: Tuple representing the available space (width, height).
        :return:                Tuple containing the size (width, height) in points.
        """
        ...
    
    def paint(self, available_space: typing.Tuple[int, int, int, int], page: Page) -> None:
        """
        Render the layout element onto the provided page using the available space.

        This function renders the layout element within the given available space on the specified page.

        :param available_space: A tuple representing the available space (left, top, right, bottom).
        :param page:            The Page object on which to render the LayoutElement.
        :return:                None.
        """
        ...
    


