services:
  web:
    build:
      context: .
      dockerfile: app/Dockerfile.app
    container_name: intranet_app
    depends_on:
      - db
    volumes:
      - ${FILES_LOCAL_PATH}:${FILES_DOCKER_PATH}  # Persistance des fichiers de contrats
      - ${PRINT_LOCAL_PATH}:${PRINT_DOCKER_PATH}
    environment:
      - DATABASE_URL=${DB_URL}
    env_file:
      - .env
    restart: always
    entrypoint: ["sh", "app/entrypoint.sh"]
    networks:
      - intranet_net

  nginx:
    image: nginx:latest
    container_name: intranet_proxy
    depends_on:
      - web
    volumes:
      - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /opt/certs:/etc/nginx/certs
    ports:
      - "443:443"  # Port HTTPS
      - "80:80"
    networks:
      - intranet_net

  db:
    image: mariadb:latest
    container_name: intranet_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - dbdata:${DB_DOCKER_PATH}
    networks:
      - intranet_net

volumes:
  dbdata:
    driver: local
    driver_opts:
      type: none
      device: ${DB_LOCAL_PATH}
      o: bind

networks:
  intranet_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
