"""
This type stub file was generated by pyright.
"""

from borb.pdf.toolkit.event import Event
from borb.pdf.toolkit.pipe import Pipe

"""
A filter class for processing PDF page content streams, specifically targeting content that appears below a specified y-coordinate on the PDF page.

This class is part of a filtering system designed to handle and manipulate portions
of a PDF content stream based on their vertical position. Using `Below`, only
content located beneath the given y-coordinate threshold is targeted, allowing for
selective manipulation or extraction of content positioned lower on the page.
"""
class Below(Pipe):
    """
    A filter class for processing PDF page content streams, specifically targeting content that appears below a specified y-coordinate on the PDF page.

    This class is part of a filtering system designed to handle and manipulate portions
    of a PDF content stream based on their vertical position. Using `Below`, only
    content located beneath the given y-coordinate threshold is targeted, allowing for
    selective manipulation or extraction of content positioned lower on the page.
    """
    def __init__(self, y: int) -> None:
        """
        Initialize a new instance of the `Below` filter.

        :param y: The y-coordinate threshold for filtering. Only elements located below
                  this value will be processed.
        """
        ...
    
    def process(self, event: Event): # -> None:
        """
        Process the given event.

        This base implementation is a no-op. Subclasses should override this method
        to provide specific processing logic.

        :param event: The event object to process.
        """
        ...
    


