"""
This type stub file was generated by pyright.
"""

from borb.pdf.toolkit.event import Event
from borb.pdf.toolkit.pipe import Pipe

"""
A filter class for processing PDF page content streams, specifically targeting content that appears below a specified image on the PDF page.

This filter is used to identify and process elements, typically text, that are positioned
beneath a designated image within the content stream. By setting an image as a
reference point, `BelowImage` enables selective extraction, manipulation, or analysis
of content that appears below that image, making it useful for document processing tasks
that depend on spatial relationships between images and surrounding text.
"""
class BelowImage(Pipe):
    """
    A filter class for processing PDF page content streams, specifically targeting content that appears below a specified image on the PDF page.

    This filter is used to identify and process elements, typically text, that are positioned
    beneath a designated image within the content stream. By setting an image as a
    reference point, `BelowImage` enables selective extraction, manipulation, or analysis
    of content that appears below that image, making it useful for document processing tasks
    that depend on spatial relationships between images and surrounding text.
    """
    def __init__(self) -> None:
        """
        Initialize the BelowImage filter.

        This constructor sets up the necessary structures for processing events related
        to content located below images. It prepares the filter to capture events as the
        PDF content streams are processed, allowing for filtering based on the position
        of content relative to images.
        """
        ...
    
    def process(self, event: Event) -> None:
        """
        Process the given event.

        This base implementation is a no-op. Subclasses should override this method
        to provide specific processing logic.

        :param event: The event object to process.
        """
        ...
    


