"""
This type stub file was generated by pyright.
"""

from borb.pdf.font.simple_font.standard_type_1_font import StandardType1Font

"""
Represents the Helvetica typeface and its properties.

The `Helvetica` class encapsulates the metrics and characteristics of the Helvetica typeface,
a widely used sans-serif font known for its clean and modern appearance.
This class is typically used to render text in PDF documents where Helvetica
is required. It provides access to font-specific properties such as width,
height, and character mapping.
"""
class Helvetica(StandardType1Font):
    """
    Represents the Helvetica typeface and its properties.

    The `Helvetica` class encapsulates the metrics and characteristics of the Helvetica typeface,
    a widely used sans-serif font known for its clean and modern appearance.
    This class is typically used to render text in PDF documents where Helvetica
    is required. It provides access to font-specific properties such as width,
    height, and character mapping.
    """
    def __init__(self) -> None:
        """
        Initialize the Helvetica font object with its specific attributes.

        The `Helvetica` class represents the Helvetica font,
        a widely used sans-serif Type1 font known for its clean and modern appearance.
        This constructor sets the font's base attributes, including its encoding, font type,
        and width for various Unicode characters.
        The font provides proportional spacing, making it suitable for a wide range of text content in PDF rendering.
        """
        ...
    
    def get_width(self, text: str, character_spacing: float = ..., font_size: float = ..., word_spacing: float = ...) -> int:
        """
        Return the total width of a text string when rendered with the font at a specific size.

        This function calculates the width of the given text string when rendered with the font
        at the specified font size.

        :param font_size:           The font size to be used for rendering.
        :param text:                The text string to calculate the width for.
        :param word_spacing:        The word spacing to be used for rendering
        :param character_spacing:   The character spacing to be used for rendering
        :return:                    The width (in points) of the text in the specified font size.
        """
        ...
    


