"""
This type stub file was generated by pyright.
"""

from borb.pdf.font.simple_font.standard_type_1_font import StandardType1Font

"""
Represents the Helvetica Italic typeface and its properties.

The Helvetica Italic typeface is a widely used sans-serif font known for its
clean and modern appearance. This class is typically used to render text in PDF
documents where Helvetica Italic is required.

It provides access to font-specific properties such as width, height, and character
mapping.
"""
class HelveticaItalic(StandardType1Font):
    """
    Represents the Helvetica Italic typeface and its properties.

    The Helvetica Italic typeface is a widely used sans-serif font known for its
    clean and modern appearance. This class is typically used to render text in PDF
    documents where Helvetica Italic is required.

    It provides access to font-specific properties such as width, height, and character
    mapping.
    """
    def __init__(self) -> None:
        """
        Initialize the Helvetica-Oblique (Italic) font object with its specific attributes.

        The `HelveticaItalic` class represents the Helvetica-Oblique font,
        a Type1 italic (oblique) variant of the Helvetica font.
        This constructor sets the font's base attributes, including its encoding, font type,
        and width for various Unicode characters.
        The font uses proportional spacing and provides an italic style for slanted text,
        making it ideal for emphasis or stylistic content.
        """
        ...
    
    def get_width(self, text: str, character_spacing: float = ..., font_size: float = ..., word_spacing: float = ...) -> int:
        """
        Return the total width of a text string when rendered with the font at a specific size.

        This function calculates the width of the given text string when rendered with the font
        at the specified font size.

        :param font_size:           The font size to be used for rendering.
        :param text:                The text string to calculate the width for.
        :param word_spacing:        The word spacing to be used for rendering
        :param character_spacing:   The character spacing to be used for rendering
        :return:                    The width (in points) of the text in the specified font size.
        """
        ...
    


