"""
This type stub file was generated by pyright.
"""

"""
A class for applying ASCII85 decoding to data in a PDF document.

The `ASCII85Decode` class implements the ASCII85 (also known as Base85) decoding scheme,
which is a form of binary-to-text encoding commonly used in PDF files. This method allows
the decoding of ASCII-encoded data that was originally compressed or encoded in ASCII85
format. It converts the ASCII85-encoded string back into the original binary data.

ASCII85 decoding is used in PDFs for more efficient storage of binary data, such as images
or streams, by representing binary information as a set of ASCII characters.
"""
class ASCII85Decode:
    """
    A class for applying ASCII85 decoding to data in a PDF document.

    The `ASCII85Decode` class implements the ASCII85 (also known as Base85) decoding scheme,
    which is a form of binary-to-text encoding commonly used in PDF files. This method allows
    the decoding of ASCII-encoded data that was originally compressed or encoded in ASCII85
    format. It converts the ASCII85-encoded string back into the original binary data.

    ASCII85 decoding is used in PDFs for more efficient storage of binary data, such as images
    or streams, by representing binary information as a set of ASCII characters.
    """
    @staticmethod
    def decode(bytes_in: bytes) -> bytes:
        """
        Decode data encoded in ASCII85 (Base85) representation.

        This method takes an input byte sequence that has been encoded using ASCII85
        encoding and decodes it back into the original binary data. ASCII85 is a method of
        representing binary data using printable ASCII characters, and is commonly used
        in PDF files for compressing or encoding binary data such as images or streams.

        :param bytes_in: The byte sequence that is encoded in ASCII85 format.
        :return: The decoded binary data as a byte sequence.
        """
        ...
    


