"""Ajout de la table 13_factures

Revision ID: c8293d28c674
Revises: b5f240cb2287
Create Date: 2025-09-17 16:54:01.832919

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'c8293d28c674'
down_revision: Union[str, Sequence[str], None] = 'b5f240cb2287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Création de la table '13_factures' directement par SQL Alchemy
    # Pas de modification à prévoir par Alembic
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Suppression de la table '13_factures'
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
