"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.primitives import PDFType
from borb.pdf.visitor.read.read_visitor import ReadVisitor

"""
Visitor class for reading and parsing list structures in a PDF byte stream.

`ListVisitor` extends `ReadVisitor` to identify and process list structures
within a PDF, specifically targeting arrays of values as defined by the PDF
specification. Using the visitor pattern, `ListVisitor` traverses nodes in
the PDF document tree, converting recognized list structures into corresponding
Python lists, with each element processed and converted based on its type.
"""
class ListVisitor(ReadVisitor):
    """
    Visitor class for reading and parsing list structures in a PDF byte stream.

    `ListVisitor` extends `ReadVisitor` to identify and process list structures
    within a PDF, specifically targeting arrays of values as defined by the PDF
    specification. Using the visitor pattern, `ListVisitor` traverses nodes in
    the PDF document tree, converting recognized list structures into corresponding
    Python lists, with each element processed and converted based on its type.
    """
    __LIST_CLOSE_BRACKETS = ...
    __LIST_OPEN_BRACKETS = ...
    __SPACE = ...
    def visit(self, node: typing.Union[int, PDFType]) -> typing.Optional[typing.Tuple[PDFType, int]]:
        """
        Traverse the PDF document tree using the visitor pattern.

        This method is called when a node does not have a specialized handler.
        Subclasses can override this method to provide default behavior or logging
        for unsupported nodes. If any operation is performed on the node (e.g.,
        writing or persisting), the method returns `True`. Otherwise, it returns
        `False` to indicate that the visitor did not process the node.

        :param node:    the node (PDFType) to be processed
        :return:        True if the visitor processed the node False otherwise
        """
        ...
    


