"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.primitives import PDFType
from borb.pdf.visitor.read.read_visitor import ReadVisitor

"""
Visitor class for reading and parsing name objects in a PDF byte stream.

`NameVisitor` extends `ReadVisitor` to identify and process name objects within
a PDF, converting these into corresponding Python strings. Using the visitor pattern,
`NameVisitor` traverses PDF nodes and extracts name objects according to the PDF
specification, facilitating structured parsing of named resources and keys.
"""
class NameVisitor(ReadVisitor):
    """
    Visitor class for reading and parsing name objects in a PDF byte stream.

    `NameVisitor` extends `ReadVisitor` to identify and process name objects within
    a PDF, converting these into corresponding Python strings. Using the visitor pattern,
    `NameVisitor` traverses PDF nodes and extracts name objects according to the PDF
    specification, facilitating structured parsing of named resources and keys.
    """
    def visit(self, node: typing.Union[int, PDFType]) -> typing.Optional[typing.Tuple[PDFType, int]]:
        """
        Traverse the PDF document tree using the visitor pattern.

        This method is called when a node does not have a specialized handler.
        Subclasses can override this method to provide default behavior or logging
        for unsupported nodes. If any operation is performed on the node (e.g.,
        writing or persisting), the method returns `True`. Otherwise, it returns
        `False` to indicate that the visitor did not process the node.

        :param node:    the node (PDFType) to be processed
        :return:        True if the visitor processed the node False otherwise
        """
        ...
    


