"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.primitives import PDFType
from borb.pdf.visitor.read.read_visitor import ReadVisitor

"""
A `ReferenceVisitor` implementation that skips reference lookups during PDF processing.

The `NoOpReferenceVisitor` is a specialized visitor class used when processing object streams
in a PDF. Unlike the standard `ReferenceVisitor`, it does not attempt to resolve references
to other objects within the PDF file. This behavior is necessary when handling object streams
because the references embedded within these streams can only be resolved later, outside the
immediate context of the bytes inside the stream.

This class is particularly useful in situations where resolving references prematurely may
lead to errors or incorrect behavior, such as when parsing incremental updates or deferred
content in PDFs.
"""
class NoOpReferenceVisitor(ReadVisitor):
    """
    A `ReferenceVisitor` implementation that skips reference lookups during PDF processing.

    The `NoOpReferenceVisitor` is a specialized visitor class used when processing object streams
    in a PDF. Unlike the standard `ReferenceVisitor`, it does not attempt to resolve references
    to other objects within the PDF file. This behavior is necessary when handling object streams
    because the references embedded within these streams can only be resolved later, outside the
    immediate context of the bytes inside the stream.

    This class is particularly useful in situations where resolving references prematurely may
    lead to errors or incorrect behavior, such as when parsing incremental updates or deferred
    content in PDFs.
    """
    def visit(self, node: typing.Union[int, PDFType]) -> typing.Optional[typing.Tuple[PDFType, int]]:
        """
        Traverse the PDF document tree using the visitor pattern.

        This method is called when a node does not have a specialized handler.
        Subclasses can override this method to provide default behavior or logging
        for unsupported nodes. If any operation is performed on the node (e.g.,
        writing or persisting), the method returns `True`. Otherwise, it returns
        `False` to indicate that the visitor did not process the node.

        :param node:    the node (PDFType) to be processed
        :return:        True if the visitor processed the node False otherwise
        """
        ...
    


