"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.primitives import PDFType
from borb.pdf.visitor.read.xref_visitor import XRefVisitor

"""
Visitor class for reading and parsing uncompressed cross-reference tables (XRef) in a PDF.

`PlaintextXRefVisitor` is specialized to locate and interpret plaintext (uncompressed)
cross-reference tables, which are integral to defining the byte offsets of objects
within the PDF file. Using the visitor pattern, `PlaintextXRefVisitor` parses each
entry in the XRef table, extracting information about object positions to enable
efficient access and retrieval during PDF parsing.

This class:
- Identifies the `xref` keyword marking the start of an uncompressed XRef table
- Processes entries with object offsets, generation numbers, and usage flags
- Builds an index mapping object numbers to their byte positions in the file,
  facilitating object lookup and retrieval

`PlaintextXRefVisitor` is essential for accurately mapping the structure of
PDFs that use uncompressed XRef tables, supporting document reconstruction and
efficient navigation within the PDF byte stream.
"""
class PlaintextXRefVisitor(XRefVisitor):
    """
    Visitor class for reading and parsing uncompressed cross-reference tables (XRef) in a PDF.

    `PlaintextXRefVisitor` is specialized to locate and interpret plaintext (uncompressed)
    cross-reference tables, which are integral to defining the byte offsets of objects
    within the PDF file. Using the visitor pattern, `PlaintextXRefVisitor` parses each
    entry in the XRef table, extracting information about object positions to enable
    efficient access and retrieval during PDF parsing.

    This class:
    - Identifies the `xref` keyword marking the start of an uncompressed XRef table
    - Processes entries with object offsets, generation numbers, and usage flags
    - Builds an index mapping object numbers to their byte positions in the file,
      facilitating object lookup and retrieval

    `PlaintextXRefVisitor` is essential for accurately mapping the structure of
    PDFs that use uncompressed XRef tables, supporting document reconstruction and
    efficient navigation within the PDF byte stream.
    """
    def visit(self, node: typing.Union[int, PDFType]) -> typing.Optional[typing.Tuple[PDFType, int]]:
        """
        Traverse the PDF document tree using the visitor pattern.

        This method is called when a node does not have a specialized handler.
        Subclasses can override this method to provide default behavior or logging
        for unsupported nodes. If any operation is performed on the node (e.g.,
        writing or persisting), the method returns `True`. Otherwise, it returns
        `False` to indicate that the visitor did not process the node.

        :param node:    the node (PDFType) to be processed
        :return:        True if the visitor processed the node False otherwise
        """
        ...
    


