"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.layout_element.layout_element import LayoutElement
from borb.pdf.page import Page
from borb.pdf.page_layout.page_layout import PageLayout

"""
Represents a layout for organizing content into multiple columns on a PDF page.

The `MultiColumnLayout` class provides a flexible way to arrange content in
multiple columns, such as two, three, or more, depending on the needs of the
document. It is designed to manage the flow of text and other elements across
these columns, ensuring proper alignment and balance. Content automatically
flows from one column to the next and, if necessary, across pages.

This layout is ideal for presenting structured information in a visually
appealing manner, improving readability and allowing for an even distribution
of content on the page.
"""
class MultiColumnLayout(PageLayout):
    """
    Represents a layout for organizing content into multiple columns on a PDF page.

    The `MultiColumnLayout` class provides a flexible way to arrange content in
    multiple columns, such as two, three, or more, depending on the needs of the
    document. It is designed to manage the flow of text and other elements across
    these columns, ensuring proper alignment and balance. Content automatically
    flows from one column to the next and, if necessary, across pages.

    This layout is ideal for presenting structured information in a visually
    appealing manner, improving readability and allowing for an even distribution
    of content on the page.
    """
    def __init__(self, page: Page, inter_column_margin: typing.Optional[int] = ..., margin_bottom: typing.Optional[int] = ..., margin_left: typing.Optional[int] = ..., margin_right: typing.Optional[int] = ..., margin_top: typing.Optional[int] = ..., number_of_columns: int = ...) -> None:
        """
        Initialize the MultiColumnLayout with the specified page and number of columns.

        The `MultiColumnLayout` constructor sets up a layout that organizes content
        into multiple columns on the provided PDF page.
        This layout is designed to facilitate the presentation of information
        in a structured and visually appealing manner.
        It automatically calculates the dimensions and margins for the specified number of columns,
        ensuring that content flows smoothly across the columns while maintaining appropriate spacing.

        :param page:                An instance of the `Page` class that represents the page where the multi-column layout will be applied.
                                    This instance provides the dimensions necessary for layout configuration.
        :param number_of_columns:   An integer that specifies the number of columns for the layout.
                                    The default value is 2, but it can be adjusted to accommodate different content requirements.
        """
        ...
    
    def append_layout_element(self, layout_element: LayoutElement) -> MultiColumnLayout:
        """
        Append a layout element to the multi-column layout.

        This method adds the specified layout element, such as text, images, or other
        visual components, to the current multi-column layout. The element is
        positioned within the available columns and will flow from one column to
        the next if needed, maintaining the structured layout of the content.

        :param layout_element:   the LayoutElement to be added
        :return:    Self, this allows for method-chaining
        """
        ...
    
    def next_column(self) -> MultiColumnLayout:
        """
        Move to the next column in the layout, adding a new page if necessary.

        This method manages the transition to the next column in a multi-column layout.
        If there are no more columns on the current page, a new page is added,
        and the column index is reset to the first column. The layout manager
        updates its internal state to reflect the transition.

        :return: The updated MultiColumnLayout instance.
        """
        ...
    
    def next_page(self) -> MultiColumnLayout:
        """
        Add a new page to the layout and reset column tracking.

        This method handles transitioning to a new page in the multi-column layout.
        It appends a new page to the associated document, resets the column index,
        and updates the internal layout state to reflect the change.

        :return: The updated MultiColumnLayout instance.
        """
        ...
    


