"""
This type stub file was generated by pyright.
"""

from borb.pdf.font.simple_font.standard_type_1_font import StandardType1Font

"""
Represents the Times Italic typeface and its properties.

The Times Italic class encapsulates the metrics and characteristics of the Times typeface,
a widely used serif font known for its readability and elegance. This class is typically used to
render text in PDF documents where Times Italic is required.

It provides access to font-specific properties such as width, height, and character mapping.
"""
class TimesItalic(StandardType1Font):
    """
    Represents the Times Italic typeface and its properties.

    The Times Italic class encapsulates the metrics and characteristics of the Times typeface,
    a widely used serif font known for its readability and elegance. This class is typically used to
    render text in PDF documents where Times Italic is required.

    It provides access to font-specific properties such as width, height, and character mapping.
    """
    def __init__(self) -> None:
        """
        Initialize the Times Italic font object with its specific attributes.

        The `TimesItalic` class represents the Times Italic font,
        providing an italicized version of the classic Times font.
        This constructor sets the font's base attributes, including its encoding, font type,
        and width for various Unicode characters.
        The italic style is often used for emphasis, making it suitable for citations and stylistic text.
        """
        ...
    
    def get_width(self, text: str, character_spacing: float = ..., font_size: float = ..., word_spacing: float = ...) -> int:
        """
        Return the total width of a text string when rendered with the font at a specific size.

        This function calculates the width of the given text string when rendered with the font
        at the specified font size.

        :param font_size:           The font size to be used for rendering.
        :param text:                The text string to calculate the width for.
        :param word_spacing:        The word spacing to be used for rendering
        :param character_spacing:   The character spacing to be used for rendering
        :return:                    The width (in points) of the text in the specified font size.
        """
        ...
    


