"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.visitor.write_new.write_new_visitor import WriteNewVisitor

"""
A visitor that injects an sRGB OutputIntent into a PDF document to ensure PDF/A compliance.

This visitor class modifies the PDF document by adding an OutputIntent dictionary
to the document's catalog. The OutputIntent ensures that any DeviceRGB colors are
properly defined with an embedded sRGB ICC profile, which is a requirement for PDF/A-1
compliance. PDF/A-1 standards prohibit the use of DeviceRGB without an associated
OutputIntent, and this visitor ensures that the document conforms to that specification.

The class uses the visitor pattern to traverse and modify the PDF document, adding
the required OutputIntent information if it's not already present. It performs the
injection only once per session to avoid redundant operations.
"""
class InjectsRGBOutputIntentVisitor(WriteNewVisitor):
    """
    A visitor that injects an sRGB OutputIntent into a PDF document to ensure PDF/A compliance.

    This visitor class modifies the PDF document by adding an OutputIntent dictionary
    to the document's catalog. The OutputIntent ensures that any DeviceRGB colors are
    properly defined with an embedded sRGB ICC profile, which is a requirement for PDF/A-1
    compliance. PDF/A-1 standards prohibit the use of DeviceRGB without an associated
    OutputIntent, and this visitor ensures that the document conforms to that specification.

    The class uses the visitor pattern to traverse and modify the PDF document, adding
    the required OutputIntent information if it's not already present. It performs the
    injection only once per session to avoid redundant operations.
    """
    def visit(self, node: typing.Any) -> typing.Optional[typing.Any]:
        """
        Traverse the PDF document tree using the visitor pattern.

        This method is called when a node does not have a specialized handler.
        Subclasses can override this method to provide default behavior or logging
        for unsupported nodes. If any operation is performed on the node (e.g.,
        writing or persisting), the method returns `True`. Otherwise, it returns
        `False` to indicate that the visitor did not process the node.

        :param node:    the node (PDFType) to be processed
        :return:        True if the visitor processed the node False otherwise
        """
        ...
    


