"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.visitor.write_new.write_new_visitor import WriteNewVisitor

"""
A visitor that injects a MarkInfo dictionary into a PDF to improve accessibility and ensure tagged PDF compliance.

This visitor modifies the document's catalog by adding or updating the /MarkInfo
entry, which indicates the presence of tagged content. The /MarkInfo dictionary
is essential for PDF/UA (Universal Accessibility) compliance and helps assistive
technologies interpret the document structure correctly.

The visitor follows the visitor pattern to traverse and modify the document,
ensuring that the /MarkInfo dictionary is injected if it is missing. If an entry
already exists, it is left unchanged unless an update is required.
"""
class InjectMarkInfoVisitor(WriteNewVisitor):
    """
    A visitor that injects a MarkInfo dictionary into a PDF to improve accessibility and ensure tagged PDF compliance.

    This visitor modifies the document's catalog by adding or updating the /MarkInfo
    entry, which indicates the presence of tagged content. The /MarkInfo dictionary
    is essential for PDF/UA (Universal Accessibility) compliance and helps assistive
    technologies interpret the document structure correctly.

    The visitor follows the visitor pattern to traverse and modify the document,
    ensuring that the /MarkInfo dictionary is injected if it is missing. If an entry
    already exists, it is left unchanged unless an update is required.
    """
    def visit(self, node: typing.Any) -> typing.Optional[typing.Any]:
        """
        Traverse the PDF document tree using the visitor pattern.

        This method is called when a node does not have a specialized handler.
        Subclasses can override this method to provide default behavior or logging
        for unsupported nodes. If any operation is performed on the node (e.g.,
        writing or persisting), the method returns `True`. Otherwise, it returns
        `False` to indicate that the visitor did not process the node.

        :param node:    the node (PDFType) to be processed
        :return:        True if the visitor processed the node False otherwise
        """
        ...
    


