"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.visitor.node_visitor import NodeVisitor
from borb.pdf.visitor.write_new.write_new_visitor import WriteNewVisitor

"""
Visitor class for converting specific string objects to name objects in a PDF document.

`ReplaceStrByNameVisitor` is a preparatory step in the PDF serialization
process, ensuring that dictionary keys or values that require name objects
(as defined by the PDF specification) are properly set. Users interacting
with the PDF structure may inadvertently assign regular strings to such
fields, as they manipulate the PDF document similarly to a JSON-like
structure.

This visitor iterates through the document, identifying and replacing
string objects with name objects wherever required. This automatic conversion
helps maintain PDF format compliance without requiring users to manually
distinguish between string and name object types.
"""
class ReplaceStrByNameVisitor(WriteNewVisitor):
    """
    Visitor class for converting specific string objects to name objects in a PDF document.

    `ReplaceStrByNameVisitor` is a preparatory step in the PDF serialization
    process, ensuring that dictionary keys or values that require name objects
    (as defined by the PDF specification) are properly set. Users interacting
    with the PDF structure may inadvertently assign regular strings to such
    fields, as they manipulate the PDF document similarly to a JSON-like
    structure.

    This visitor iterates through the document, identifying and replacing
    string objects with name objects wherever required. This automatic conversion
    helps maintain PDF format compliance without requiring users to manually
    distinguish between string and name object types.
    """
    __KNOWN_NAMES: typing.List[str] = ...
    def __init__(self, root: typing.Optional[NodeVisitor] = ...) -> None:
        """
        Initialize a new instance of `ReplaceStrByNameVisitor`.

        This constructor sets up the visitor to perform name-object replacement in a
        PDF document. It accepts an optional root `NodeVisitor` to provide context
        within a visitor hierarchy. An internal flag, `__has_been_used`, tracks whether
        this visitor has been applied, enabling it to operate only once per session.

        :param root: An optional `NodeVisitor` instance representing the root of the visitor
                     hierarchy, often used to manage shared context or data among multiple
                     visitors. Defaults to `None`.
        """
        ...
    
    def visit(self, node: typing.Any) -> bool:
        """
        Traverse the PDF document tree using the visitor pattern.

        This method is called when a node does not have a specialized handler.
        Subclasses can override this method to provide default behavior or logging
        for unsupported nodes. If any operation is performed on the node (e.g.,
        writing or persisting), the method returns `True`. Otherwise, it returns
        `False` to indicate that the visitor did not process the node.

        :param node:    the node (PDFType) to be processed
        :return:        True if the visitor processed the node False otherwise
        """
        ...
    


