"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.visitor.write_new.write_new_visitor import WriteNewVisitor

"""
A visitor class for handling the writing or persistence of stream objects within the PDF structure.

Stream objects in PDF documents typically represent binary data, such as images, fonts,
or embedded files. This class is responsible for traversing nodes that contain stream
data and writing them in the appropriate binary format. It ensures that the data is
correctly encoded, compressed (if necessary), and stored in compliance with PDF standards.
"""
class StreamVisitor(WriteNewVisitor):
    """
    A visitor class for handling the writing or persistence of stream objects within the PDF structure.

    Stream objects in PDF documents typically represent binary data, such as images, fonts,
    or embedded files. This class is responsible for traversing nodes that contain stream
    data and writing them in the appropriate binary format. It ensures that the data is
    correctly encoded, compressed (if necessary), and stored in compliance with PDF standards.
    """
    __FORCE_COMPRESSION_WHEN_FILTER_IS_NOT_SET: bool = ...
    def visit(self, node: typing.Any) -> bool:
        """
        Traverse the PDF document tree using the visitor pattern.

        This method is called when a node does not have a specialized handler.
        Subclasses can override this method to provide default behavior or logging
        for unsupported nodes. If any operation is performed on the node (e.g.,
        writing or persisting), the method returns `True`. Otherwise, it returns
        `False` to indicate that the visitor did not process the node.

        :param node:    the node (PDFType) to be processed
        :return:        True if the visitor processed the node False otherwise
        """
        ...
    


