"""
This type stub file was generated by pyright.
"""

from borb.pdf.font.simple_font.standard_type_1_font import StandardType1Font

"""
Represents the ZapfDingbats typeface and its properties.

The ZapfDingbats class encapsulates the metrics and characteristics of the
ZapfDingbats typeface, a widely used symbol font. This class is typically used
to render text in PDF documents where ZapfDingbats is required.

It provides access to font-specific properties such as width, height, and
character mapping.
"""
class ZapfDingbats(StandardType1Font):
    """
    Represents the ZapfDingbats typeface and its properties.

    The ZapfDingbats class encapsulates the metrics and characteristics of the
    ZapfDingbats typeface, a widely used symbol font. This class is typically used
    to render text in PDF documents where ZapfDingbats is required.

    It provides access to font-specific properties such as width, height, and
    character mapping.
    """
    def __init__(self) -> None:
        """
        Initialize the ZapfDingbats font class.

        This constructor sets up the necessary internal mappings and data structures to enable the retrieval of
        character IDs (CIDs) for the ZapfDingbats font. The class provides functionality to map Unicode characters
        to their corresponding CIDs within this specialized symbol font.
        """
        ...
    
    def get_width(self, text: str, character_spacing: float = ..., font_size: float = ..., word_spacing: float = ...) -> int:
        """
        Return the total width of a text string when rendered with the font at a specific size.

        This function calculates the width of the given text string when rendered with the font
        at the specified font size.

        :param font_size:           The font size to be used for rendering.
        :param text:                The text string to calculate the width for.
        :param word_spacing:        The word spacing to be used for rendering
        :param character_spacing:   The character spacing to be used for rendering
        :return:                    The width (in points) of the text in the specified font size.
        """
        ...
    


