"""
This type stub file was generated by pyright.
"""

import pathlib
import typing
from borb.pdf.document import Document

"""
Represents a PDF document, providing methods for reading and writing PDF files.

The `PDF` class simplifies PDF handling by offering an interface for reading,
writing, and managing content within PDF documents. It abstracts the complexities
of PDF structure, allowing users to easily manipulate documents.
"""
class PDF:
    """
    Represents a PDF document, providing methods for reading and writing PDF files.

    The `PDF` class simplifies PDF handling by offering an interface for reading,
    writing, and managing content within PDF documents. It abstracts the complexities
    of PDF structure, allowing users to easily manipulate documents.
    """
    @staticmethod
    def read(where_from: typing.Union[str, pathlib.Path]) -> typing.Optional[Document]:
        """
        Read a PDF file from the specified location and convert it to a `Document` object.

        This method opens and reads a PDF file from disk, parses its contents, and
        converts the text and structure into a `Document` object. The input file
        location can be provided as a string or `pathlib.Path` object. The resulting
        `Document` object allows further manipulation and analysis of the PDF’s content
        within the application.

        :param where_from: The file path to the PDF, specified as a string or `pathlib.Path` object, indicating the location of the PDF file to read.
        :return: A `Document` object containing the parsed contents of the PDF, structured for further processing or display.
        """
        ...
    
    @staticmethod
    def write(what: Document, where_to: typing.Union[pathlib.Path, str, typing.BinaryIO]) -> None:
        """
        Write the specified Document to a PDF file.

        This method saves the provided Document object into a PDF format at the
        location specified by the file path. The file path can be a string or
        a pathlib.Path object. If the file already exists, it will be overwritten.

        :param where_to:    the path (or pathlib.Path) where the Document needs to be stored
        :param what:        the document to be stored
        :return:    None
        """
        ...
    


