"""
This type stub file was generated by pyright.
"""

from borb.pdf.font.simple_font.standard_type_1_font import StandardType1Font

"""
Represents the bold italic variant of the Courier typeface.

The `CourierBoldItalic` class encapsulates the metrics and characteristics of the Courier Bold Italic typeface,
a widely used monospaced font. This class is primarily used for rendering bold italic text in PDF documents
where the Courier Bold Italic font is required. It provides access to font-specific properties, including
width, height, and character mapping, ensuring accurate text layout and rendering.
"""
class CourierBoldItalic(StandardType1Font):
    """
    Represents the bold italic variant of the Courier typeface.

    The `CourierBoldItalic` class encapsulates the metrics and characteristics of the Courier Bold Italic typeface,
    a widely used monospaced font. This class is primarily used for rendering bold italic text in PDF documents
    where the Courier Bold Italic font is required. It provides access to font-specific properties, including
    width, height, and character mapping, ensuring accurate text layout and rendering.
    """
    def __init__(self) -> None:
        """
        Initialize the Courier-BoldOblique font object with its specific attributes.

        The `CourierBoldItalic` class represents the Courier-BoldOblique font,
        a Type1 font with bold and oblique styling.
        This constructor sets the font's base attributes, including its encoding, font type,
        and width for various Unicode characters. The font is primarily used for PDF rendering.

        The Unicode-to-width mapping defines the fixed-width (600 units) for all characters,
        ensuring consistent text alignment and spacing.
        """
        ...
    
    def get_width(self, text: str, character_spacing: float = ..., font_size: float = ..., word_spacing: float = ...) -> int:
        """
        Return the total width of a text string when rendered with the font at a specific size.

        This function calculates the width of the given text string when rendered with the font
        at the specified font size.

        :param font_size:           The font size to be used for rendering.
        :param text:                The text string to calculate the width for.
        :param word_spacing:        The word spacing to be used for rendering
        :param character_spacing:   The character spacing to be used for rendering
        :return:                    The width (in points) of the text in the specified font size.
        """
        ...
    


