"""
This type stub file was generated by pyright.
"""

from borb.pdf.font.simple_font.standard_type_1_font import StandardType1Font

"""
Represents the Courier typeface and its properties.

The `Courier` class encapsulates the metrics and characteristics of the Courier typeface,
a widely used monospaced font. This class is primarily used for rendering text in PDF documents
where the Courier font is required. It provides access to font-specific properties,
including width, height, and character mapping, enabling accurate text layout and rendering.
"""
class Courier(StandardType1Font):
    """
    Represents the Courier typeface and its properties.

    The `Courier` class encapsulates the metrics and characteristics of the Courier typeface,
    a widely used monospaced font. This class is primarily used for rendering text in PDF documents
    where the Courier font is required. It provides access to font-specific properties,
    including width, height, and character mapping, enabling accurate text layout and rendering.
    """
    def __init__(self) -> None:
        """
        Initialize the Courier font object with its specific attributes.

        The `Courier` class represents the standard Courier font, a monospaced Type1 font used in PDF rendering.
        This constructor sets the font's base attributes, including its encoding, font type,
        and width for various Unicode characters.
        The font maintains fixed-width spacing across all characters (600 units), ensuring consistent alignment.
        """
        ...
    
    def get_width(self, text: str, character_spacing: float = ..., font_size: float = ..., word_spacing: float = ...) -> int:
        """
        Return the total width of a text string when rendered with the font at a specific size.

        This function calculates the width of the given text string when rendered with the font
        at the specified font size.

        :param font_size:           The font size to be used for rendering.
        :param text:                The text string to calculate the width for.
        :param word_spacing:        The word spacing to be used for rendering
        :param character_spacing:   The character spacing to be used for rendering
        :return:                    The width (in points) of the text in the specified font size.
        """
        ...
    


