"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.page import Page
from borb.pdf.primitives import PDFType
from borb.pdf.toolkit.source.operator.operator import Operator
from borb.pdf.toolkit.source.operator.source import Source

"""
The 'y' operator: Append a cubic Bézier curve to the current path.

The 'y' operator is used in a PDF content stream to append a cubic Bézier curve to the
current path. The curve extends from the current point to the point (x3, y3), with the
control points (x1, y1) and (x2, y2) defining the shape of the curve. After executing the
'yc' operator, the new current point is set to (x3, y3), which is the endpoint of the curve.

This operator is part of the path construction process, allowing for the creation of
smooth, curved paths in a PDF document. Cubic Bézier curves are widely used for defining
complex shapes and curves in vector graphics, providing precise control over the curvature.

Note:
    The 'y' operator is similar to the 'c' operator, which also appends a cubic Bézier
    curve to the path, but the 'y' operator requires different control points. The
    'y' operator modifies the current point to the final endpoint of the curve.
    For more information on Bézier curves, refer to section 8.5.2.2 of the PDF specification.
"""
class Operatory(Operator):
    """
    The 'y' operator: Append a cubic Bézier curve to the current path.

    The 'y' operator is used in a PDF content stream to append a cubic Bézier curve to the
    current path. The curve extends from the current point to the point (x3, y3), with the
    control points (x1, y1) and (x2, y2) defining the shape of the curve. After executing the
    'yc' operator, the new current point is set to (x3, y3), which is the endpoint of the curve.

    This operator is part of the path construction process, allowing for the creation of
    smooth, curved paths in a PDF document. Cubic Bézier curves are widely used for defining
    complex shapes and curves in vector graphics, providing precise control over the curvature.

    Note:
        The 'y' operator is similar to the 'c' operator, which also appends a cubic Bézier
        curve to the path, but the 'y' operator requires different control points. The
        'y' operator modifies the current point to the final endpoint of the curve.
        For more information on Bézier curves, refer to section 8.5.2.2 of the PDF specification.
    """
    def apply(self, operands: typing.List[PDFType], page: Page, source: Source) -> None:
        """
        Apply the operator's logic to the given `Page`.

        This method executes the operator using the provided operands, applying its
        effects to the specified `Page` via the `Source` processor. Subclasses should
        override this method to implement specific operator behavior.

        :param page: The `Page` object to which the operator is applied.
        :param source: The `Source` object managing the content stream.
        :param operands: A list of `PDFType` objects representing the operator's operands.
        """
        ...
    
    def get_name(self) -> str:
        """
        Retrieve the name of the operator.

        The name is a string identifier that corresponds to the operator
        in a PDF content stream (e.g., "BT" for Begin Text or "q" for Save Graphics State).

        :return: The name of the operator as a string.
        """
        ...
    
    def get_number_of_operands(self) -> int:
        """
        Retrieve the expected number of operands for this operator.

        The number of operands varies depending on the operator's purpose. For example,
        some operators might require no operands, while others may require multiple.

        :return: The number of operands expected by this operator as an integer.
        """
        ...
    


