"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.page import Page
from borb.pdf.primitives import PDFType
from borb.pdf.toolkit.source.operator.operator import Operator
from borb.pdf.toolkit.source.operator.source import Source

"""
The 're' operator: Append a rectangle to the current path.

This operator appends a rectangle to the current path as a complete subpath.
The rectangle is defined by its lower-left corner at coordinates (x, y),
with the specified width and height, all in user space coordinates.

The operation `x y width height re` is equivalent to the following sequence:
    - Move to (x, y) with the 'm' operator.
    - Draw a line to (x + width, y) with the 'l' operator.
    - Draw a line to (x + width, y + height) with the 'l' operator.
    - Draw a line to (x, y + height) with the 'l' operator.
    - Close the subpath with the 'h' operator.

This operator is commonly used to create rectangular shapes within a path for
subsequent filling, stroking, or clipping operations.

Note:
    This operator creates a closed subpath representing a rectangle. If the rectangle
    needs to be filled, stroked, or clipped, additional operators such as 'f', 'S', or 'n'
    should follow.
"""
class Operatorre(Operator):
    """
    The 're' operator: Append a rectangle to the current path.

    This operator appends a rectangle to the current path as a complete subpath.
    The rectangle is defined by its lower-left corner at coordinates (x, y),
    with the specified width and height, all in user space coordinates.

    The operation `x y width height re` is equivalent to the following sequence:
        - Move to (x, y) with the 'm' operator.
        - Draw a line to (x + width, y) with the 'l' operator.
        - Draw a line to (x + width, y + height) with the 'l' operator.
        - Draw a line to (x, y + height) with the 'l' operator.
        - Close the subpath with the 'h' operator.

    This operator is commonly used to create rectangular shapes within a path for
    subsequent filling, stroking, or clipping operations.

    Note:
        This operator creates a closed subpath representing a rectangle. If the rectangle
        needs to be filled, stroked, or clipped, additional operators such as 'f', 'S', or 'n'
        should follow.
    """
    def apply(self, operands: typing.List[PDFType], page: Page, source: Source) -> None:
        """
        Apply the operator's logic to the given `Page`.

        This method executes the operator using the provided operands, applying its
        effects to the specified `Page` via the `Source` processor. Subclasses should
        override this method to implement specific operator behavior.

        :param page: The `Page` object to which the operator is applied.
        :param source: The `Source` object managing the content stream.
        :param operands: A list of `PDFType` objects representing the operator's operands.
        """
        ...
    
    def get_name(self) -> str:
        """
        Retrieve the name of the operator.

        The name is a string identifier that corresponds to the operator
        in a PDF content stream (e.g., "BT" for Begin Text or "q" for Save Graphics State).

        :return: The name of the operator as a string.
        """
        ...
    
    def get_number_of_operands(self) -> int:
        """
        Retrieve the expected number of operands for this operator.

        The number of operands varies depending on the operator's purpose. For example,
        some operators might require no operands, while others may require multiple.

        :return: The number of operands expected by this operator as an integer.
        """
        ...
    


