"""
This type stub file was generated by pyright.
"""

from borb.pdf.toolkit.event import Event
from borb.pdf.toolkit.pipe import Pipe

"""
A filter class for processing PDF page content streams, specifically targeting content  associated with a specified font type.

This filter identifies and processes text elements rendered using a particular font,
allowing selective extraction, manipulation, or analysis based on font style, family,
or name. `ByFont` is especially useful in cases where different fonts in a document
denote different types of information, such as headings, footnotes, or emphasized text.
"""
class ByFont(Pipe):
    """
    A filter class for processing PDF page content streams, specifically targeting content  associated with a specified font type.

    This filter identifies and processes text elements rendered using a particular font,
    allowing selective extraction, manipulation, or analysis based on font style, family,
    or name. `ByFont` is especially useful in cases where different fonts in a document
    denote different types of information, such as headings, footnotes, or emphasized text.
    """
    def __init__(self, font_name: str) -> None:
        """
        Initialize a new instance of the `ByFont` filter.

        :param font_name: The name of the font to filter for. Text elements rendered using
                          this font will be processed by this filter.
        """
        ...
    
    def process(self, event: Event) -> None:
        """
        Process the given event.

        This base implementation is a no-op. Subclasses should override this method
        to provide specific processing logic.

        :param event: The event object to process.
        """
        ...
    


