"""
This type stub file was generated by pyright.
"""

from borb.pdf.color.color import Color
from borb.pdf.toolkit.event import Event
from borb.pdf.toolkit.pipe import Pipe

"""
A filter class for processing PDF page content streams, specifically targeting text content rendered in a specified font color.

This filter identifies and processes text elements based on their color, allowing selective
extraction or manipulation of text segments that match a particular color code (e.g., RGB values).
`ByFontColor` is useful for distinguishing different types of information or emphasis in documents
where color is used to signify importance, categorization, or grouping of text.
"""
class ByFontColor(Pipe):
    """
    A filter class for processing PDF page content streams, specifically targeting text content rendered in a specified font color.

    This filter identifies and processes text elements based on their color, allowing selective
    extraction or manipulation of text segments that match a particular color code (e.g., RGB values).
    `ByFontColor` is useful for distinguishing different types of information or emphasis in documents
    where color is used to signify importance, categorization, or grouping of text.
    """
    def __init__(self, font_color: Color) -> None:
        """
        Initialize a new instance of the `ByFontColor` filter.

        :param font_color: The font color to filter for. Text elements rendered using
                          this font color will be processed by this filter.
        """
        ...
    
    def process(self, event: Event) -> None:
        """
        Process the given event.

        This base implementation is a no-op. Subclasses should override this method
        to provide specific processing logic.

        :param event: The event object to process.
        """
        ...
    


