"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.font.font import Font

"""
Represents a CIDFont Type 0 in a PDF.

The `CIDType0Font` class models a CIDFont of Type 0, a descendant font type used in
composite fonts within PDF documents. CIDFonts (Character Identifier Fonts) are designed
to support large glyph sets through the use of CIDs, which are numeric glyph identifiers
that decouple character codes from glyph representations.

CIDType0 fonts are typically used for representing CJK (Chinese, Japanese, Korean) scripts
and other large character sets where the traditional 8-bit font encodings are insufficient.
These fonts are used in conjunction with a CMap that defines the mapping between character
codes and CIDs.

This class extends the `Font` base class with additional mechanisms for handling CID
mappings, font descriptors, and system-specific attributes essential for rendering
multi-byte encoded text.
"""
class CIDType0Font(Font):
    """
    Represents a CIDFont Type 0 in a PDF.

    The `CIDType0Font` class models a CIDFont of Type 0, a descendant font type used in
    composite fonts within PDF documents. CIDFonts (Character Identifier Fonts) are designed
    to support large glyph sets through the use of CIDs, which are numeric glyph identifiers
    that decouple character codes from glyph representations.

    CIDType0 fonts are typically used for representing CJK (Chinese, Japanese, Korean) scripts
    and other large character sets where the traditional 8-bit font encodings are insufficient.
    These fonts are used in conjunction with a CMap that defines the mapping between character
    codes and CIDs.

    This class extends the `Font` base class with additional mechanisms for handling CID
    mappings, font descriptors, and system-specific attributes essential for rendering
    multi-byte encoded text.
    """
    def get_width(self, text: typing.List[typing.Tuple[int, str]], character_spacing: float = ..., font_size: float = ..., word_spacing: float = ...) -> int:
        """
        Return the total width of a text string when rendered with the font at a specific size.

        This function calculates the width of the given text string when rendered with the font
        at the specified font size.

        :param font_size:           The font size to be used for rendering.
        :param text:                The text (cid and their corresponding character name) to calculate the width for.
        :param word_spacing:        The word spacing to be used for rendering
        :param character_spacing:   The character spacing to be used for rendering
        :return:                    The width (in points) of the text in the specified font size.
        """
        ...
    


