"""
This type stub file was generated by pyright.
"""

from borb.pdf.font.font import Font

"""
Represents a composite font in a PDF.

The `CompositeFont` class is used to represent composite fonts, also known as Type 0 fonts,
in PDF documents. Composite fonts are multi-byte fonts that allow for a large number of
glyphs, making them suitable for representing complex scripts and character sets such as
Chinese, Japanese, and Korean (CJK).

This class builds upon the base `Font` class, providing additional support for handling
CIDFonts and CMaps, which map character codes to glyphs and define character encodings
for composite fonts. Composite fonts are often used in conjunction with encoding schemes
that support wide character sets.
"""
class CompositeFont(Font):
    """
    Represents a composite font in a PDF.

    The `CompositeFont` class is used to represent composite fonts, also known as Type 0 fonts,
    in PDF documents. Composite fonts are multi-byte fonts that allow for a large number of
    glyphs, making them suitable for representing complex scripts and character sets such as
    Chinese, Japanese, and Korean (CJK).

    This class builds upon the base `Font` class, providing additional support for handling
    CIDFonts and CMaps, which map character codes to glyphs and define character encodings
    for composite fonts. Composite fonts are often used in conjunction with encoding schemes
    that support wide character sets.
    """
    def get_width(self, text: str, character_spacing: float = ..., font_size: float = ..., word_spacing: float = ...) -> int:
        """
        Return the total width of a text string when rendered with the font at a specific size.

        This function calculates the width of the given text string when rendered with the font
        at the specified font size.

        :param font_size:           The font size to be used for rendering.
        :param text:                The text string to calculate the width for.
        :param word_spacing:        The word spacing to be used for rendering
        :param character_spacing:   The character spacing to be used for rendering
        :return:                    The width (in points) of the text in the specified font size.
        """
        ...
    


