"""
This type stub file was generated by pyright.
"""

import functools
import typing
from borb.pdf.color.color import Color
from borb.pdf.layout_element.layout_element import LayoutElement
from borb.pdf.page import Page

"""
Represents a PDF annotation, which supports various standard annotation types.

PDF supports several standard annotation types, as listed in Table 169. This class describes
these types and their functionalities in detail. The values in the first column of Table 169
correspond to the annotation dictionary's Subtype entry. Additionally, the third column indicates
whether the annotation is a markup annotation, as detailed in Section 12.5.6.2, “Markup Annotations.”
This class also provides information about the value of the Contents entry for different annotation types.
"""
class Annotation(LayoutElement, dict):
    """
    Represents a PDF annotation, which supports various standard annotation types.

    PDF supports several standard annotation types, as listed in Table 169. This class describes
    these types and their functionalities in detail. The values in the first column of Table 169
    correspond to the annotation dictionary's Subtype entry. Additionally, the third column indicates
    whether the annotation is a markup annotation, as detailed in Section 12.5.6.2, “Markup Annotations.”
    This class also provides information about the value of the Contents entry for different annotation types.
    """
    def __init__(self, background_color: typing.Optional[Color] = ..., border_color: typing.Optional[Color] = ..., border_dash_pattern: typing.List[int] = ..., border_dash_phase: int = ..., border_width_bottom: int = ..., border_width_left: int = ..., border_width_right: int = ..., border_width_top: int = ..., contents: typing.Optional[str] = ..., fill_color: typing.Optional[Color] = ..., horizontal_alignment: LayoutElement.HorizontalAlignment = ..., margin_bottom: int = ..., margin_left: int = ..., margin_right: int = ..., margin_top: int = ..., padding_bottom: int = ..., padding_left: int = ..., padding_right: int = ..., padding_top: int = ..., size: typing.Tuple[int, int] = ..., stroke_color: typing.Optional[Color] = ..., vertical_alignment: LayoutElement.VerticalAlignment = ...) -> None:
        """
        Initialize a new `Annotation` object for rendering annotations in a PDF document.

        This constructor allows customization of various properties related to the
        annotation's appearance and layout, including background color, border styles,
        padding, size, contents, and alignment. These properties are essential for
        defining how the annotation will be presented within the PDF.

        :param background_color:         Optional background color for the annotation.
        :param border_color:             Optional border color for the annotation.
        :param border_dash_pattern:      Dash pattern used for the annotation's border lines.
        :param border_dash_phase:        Phase offset for the dash pattern in the annotation borders.
        :param border_width_bottom:      Width of the bottom border of the annotation.
        :param border_width_left:        Width of the left border of the annotation.
        :param border_width_right:       Width of the right border of the annotation.
        :param border_width_top:         Width of the top border of the annotation.
        :param contents:                 Optional text content for the annotation.
        :param fill_color:               Optional fill color for the annotation.
        :param horizontal_alignment:      Horizontal alignment of the annotation (default is LEFT).
        :param margin_bottom:           Space between the annotation and the element below it.
        :param margin_left:             Space between the annotation and the left page margin.
        :param margin_right:            Space between the annotation and the right page margin.
        :param margin_top:              Space between the annotation and the element above it.
        :param padding_bottom:           Padding inside the annotation at the bottom.
        :param padding_left:             Padding inside the annotation on the left side.
        :param padding_right:            Padding inside the annotation on the right side.
        :param padding_top:              Padding inside the annotation at the top.
        :param size:                     Tuple representing the width and height of the annotation.
        :param stroke_color:             Optional color for the annotation's stroke (default is None).
        :param vertical_alignment:        Vertical alignment of the annotation (default is TOP).
        """
        ...
    
    @functools.cache
    def get_size(self, available_space: typing.Tuple[int, int]) -> typing.Tuple[int, int]:
        """
        Calculate and return the size of the layout element based on available space.

        This function uses the available space to compute the size (width, height)
        of the layout element in points.

        :param available_space: Tuple representing the available space (width, height).
        :return:                Tuple containing the size (width, height) in points.
        """
        ...
    
    def paint(self, available_space: typing.Tuple[int, int, int, int], page: Page) -> None:
        """
        Render the layout element onto the provided page using the available space.

        This function renders the layout element within the given available space on the specified page.

        :param available_space: A tuple representing the available space (left, top, right, bottom).
        :param page:            The Page object on which to render the LayoutElement.
        :return:                None.
        """
        ...
    


