"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.color.color import Color
from borb.pdf.layout_element.annotation.annotation import Annotation
from borb.pdf.layout_element.layout_element import LayoutElement
from borb.pdf.page import Page

"""
Represents a highlight annotation in a PDF document.

Text markup annotations can appear as highlights, underlines, strikeouts (all PDF 1.3),
or jagged (“squiggly”) underlines (PDF 1.4) in the text of a document. When opened,
they display a pop-up window containing the text of the associated note.

Table 179 shows the annotation dictionary entries specific to these types of annotations.
"""
class HighlightAnnotation(Annotation):
    """
    Represents a highlight annotation in a PDF document.

    Text markup annotations can appear as highlights, underlines, strikeouts (all PDF 1.3),
    or jagged (“squiggly”) underlines (PDF 1.4) in the text of a document. When opened,
    they display a pop-up window containing the text of the associated note.

    Table 179 shows the annotation dictionary entries specific to these types of annotations.
    """
    def __init__(self, background_color: typing.Optional[Color] = ..., border_color: typing.Optional[Color] = ..., border_dash_pattern: typing.List[int] = ..., border_dash_phase: int = ..., border_width_bottom: int = ..., border_width_left: int = ..., border_width_right: int = ..., border_width_top: int = ..., contents: typing.Optional[str] = ..., horizontal_alignment: LayoutElement.HorizontalAlignment = ..., margin_bottom: int = ..., margin_left: int = ..., margin_right: int = ..., margin_top: int = ..., padding_bottom: int = ..., padding_left: int = ..., padding_right: int = ..., padding_top: int = ..., size: typing.Tuple[int, int] = ..., stroke_color: typing.Optional[Color] = ..., vertical_alignment: LayoutElement.VerticalAlignment = ...) -> None:
        """
        Initialize a HighlightAnnotation object for adding a highlight effect on content in a PDF document.

        This annotation provides a customizable highlight effect for marking up text or content in a document.
        It includes options for setting colors, borders, and alignment, as well as margins and padding to ensure
        proper positioning and appearance. The stroke color defines the highlight color, typically set to yellow.

        :param background_color:        The background color of the annotation. Defaults to None (transparent).
        :param border_color:            The color of the annotation's border. Defaults to None.
        :param border_dash_pattern:     A list specifying the dash pattern for the border. Defaults to an empty list (solid border).
        :param border_dash_phase:       The phase offset for the border dash pattern. Defaults to 0.
        :param border_width_bottom:     The width of the bottom border of the annotation. Defaults to 0.
        :param border_width_left:       The width of the left border of the annotation. Defaults to 0.
        :param border_width_right:      The width of the right border of the annotation. Defaults to 0.
        :param border_width_top:        The width of the top border of the annotation. Defaults to 0.
        :param contents:                Optional text content to be displayed with the annotation. Defaults to None.
        :param horizontal_alignment:    The horizontal alignment of the annotation (e.g., left, center, right). Defaults to LEFT.
        :param margin_bottom:           The bottom margin of the annotation. Defaults to 0.
        :param margin_left:             The left margin of the annotation. Defaults to 0.
        :param margin_right:            The right margin of the annotation. Defaults to 0.
        :param margin_top:              The top margin of the annotation. Defaults to 0.
        :param padding_bottom:          The bottom padding inside the annotation, between the content and the border. Defaults to 0.
        :param padding_left:            The left padding inside the annotation. Defaults to 0.
        :param padding_right:           The right padding inside the annotation. Defaults to 0.
        :param padding_top:             The top padding inside the annotation. Defaults to 0.
        :param size:                    A tuple specifying the width and height of the annotation. Defaults to (100, 100).
        :param stroke_color:            The color of the highlight stroke (default is yellow). Defaults to X11Color.YELLOW_MUNSELL.
        :param vertical_alignment:      The vertical alignment of the annotation (e.g., top, middle, bottom). Defaults to TOP.
        """
        ...
    
    def paint(self, available_space: typing.Tuple[int, int, int, int], page: Page) -> None:
        """
        Render the layout element onto the provided page using the available space.

        This function renders the layout element within the given available space on the specified page.

        :param available_space: A tuple representing the available space (left, top, right, bottom).
        :param page:            The Page object on which to render the LayoutElement.
        :return:                None.
        """
        ...
    


