"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.color.color import Color
from borb.pdf.layout_element.annotation.annotation import Annotation
from borb.pdf.layout_element.layout_element import LayoutElement
from borb.pdf.layout_element.shape.shape import Shape
from borb.pdf.page import Page

"""
Represents a polyline annotation in a PDF document.

Polyline annotations (PDF 1.5) display open polygons on the page,
which may have any number of vertices connected by straight lines.
Unlike polygon annotations, the first and last vertices of a polyline
are not implicitly connected.
"""
class PolyLineAnnotation(Annotation):
    """
    Represents a polyline annotation in a PDF document.

    Polyline annotations (PDF 1.5) display open polygons on the page,
    which may have any number of vertices connected by straight lines.
    Unlike polygon annotations, the first and last vertices of a polyline
    are not implicitly connected.
    """
    def __init__(self, shape: Shape, background_color: typing.Optional[Color] = ..., border_color: typing.Optional[Color] = ..., border_dash_pattern: typing.List[int] = ..., border_dash_phase: int = ..., border_width_bottom: int = ..., border_width_left: int = ..., border_width_right: int = ..., border_width_top: int = ..., contents: typing.Optional[str] = ..., horizontal_alignment: LayoutElement.HorizontalAlignment = ..., margin_bottom: int = ..., margin_left: int = ..., margin_right: int = ..., margin_top: int = ..., padding_bottom: int = ..., padding_left: int = ..., padding_right: int = ..., padding_top: int = ..., size: typing.Tuple[int, int] = ..., stroke_color: typing.Optional[Color] = ..., vertical_alignment: LayoutElement.VerticalAlignment = ...) -> None:
        """
        Initialize a new `PolyLineAnnotation` object for rendering a polyline annotation in a PDF.

        This constructor allows customization of various layout and style properties for
        the polyline annotation, such as shape, background color, border, size,
        contents, and alignment. These properties define the appearance and positioning of
        the polyline annotation within the PDF page.

        :param shape:                    The `Shape` object that defines the polyline's strokes.
        :param background_color:         Optional background color for the polyline annotation.
        :param border_color:             Optional border color for the annotation container.
        :param border_dash_pattern:      Dash pattern used for the annotation border lines.
        :param border_dash_phase:        Phase offset for the dash pattern in the annotation borders.
        :param border_width_bottom:      Width of the bottom border of the annotation container.
        :param border_width_left:        Width of the left border of the annotation container.
        :param border_width_right:       Width of the right border of the annotation container.
        :param border_width_top:         Width of the top border of the annotation container.
        :param contents:                 Optional text content for the annotation.
        :param horizontal_alignment:     Horizontal alignment of the annotation (default is LEFT).
        :param padding_bottom:           Padding inside the annotation container at the bottom.
        :param padding_left:             Padding inside the annotation container on the left side.
        :param padding_right:            Padding inside the annotation container on the right side.
        :param padding_top:              Padding inside the annotation container at the top.
        :param size:                     Tuple representing the width and height of the annotation.
        :param stroke_color:             Color of the polyline's stroke (default is BLACK).
        :param vertical_alignment:       Vertical alignment of the annotation (default is TOP).
        """
        ...
    
    def paint(self, available_space: typing.Tuple[int, int, int, int], page: Page) -> None:
        """
        Render the layout element onto the provided page using the available space.

        This function renders the layout element within the given available space on the specified page.

        :param available_space: A tuple representing the available space (left, top, right, bottom).
        :param page:            The Page object on which to render the LayoutElement.
        :return:                None.
        """
        ...
    


