"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.color.color import Color
from borb.pdf.layout_element.annotation.annotation import Annotation
from borb.pdf.layout_element.layout_element import LayoutElement
from borb.pdf.page import Page

"""
Represents a remote go-to annotation, which is a type of link annotation.

A remote go-to annotation allows for a hypertext link to a destination outside the document
(see 12.3.2, “Destinations”) or an action to be performed (see 12.6, “Actions”).
Table 173 shows the annotation dictionary entries specific to this type of annotation.

This annotation facilitates linking to a remote Uniform Resource Identifier (URI), enabling
users to navigate to external content or resources when activated.
"""
class RemoteGoToAnnotation(Annotation):
    """
    Represents a remote go-to annotation, which is a type of link annotation.

    A remote go-to annotation allows for a hypertext link to a destination outside the document
    (see 12.3.2, “Destinations”) or an action to be performed (see 12.6, “Actions”).
    Table 173 shows the annotation dictionary entries specific to this type of annotation.

    This annotation facilitates linking to a remote Uniform Resource Identifier (URI), enabling
    users to navigate to external content or resources when activated.
    """
    def __init__(self, uri: str, background_color: typing.Optional[Color] = ..., border_color: typing.Optional[Color] = ..., border_dash_pattern: typing.List[int] = ..., border_dash_phase: int = ..., border_width_bottom: int = ..., border_width_left: int = ..., border_width_right: int = ..., border_width_top: int = ..., contents: typing.Optional[str] = ..., horizontal_alignment: LayoutElement.HorizontalAlignment = ..., margin_bottom: int = ..., margin_left: int = ..., margin_right: int = ..., margin_top: int = ..., padding_bottom: int = ..., padding_left: int = ..., padding_right: int = ..., padding_top: int = ..., size: typing.Tuple[int, int] = ..., vertical_alignment: LayoutElement.VerticalAlignment = ...) -> None:
        """
        Initialize a remote GoTo annotation that links to a destination in another document or webpage.

        This constructor sets up a remote GoTo annotation, allowing users to create a clickable
        link that navigates to a specified destination in an external PDF document. You can customize
        the appearance of the annotation with various visual properties, including background and
        border colors, as well as dimensions.

        :param background_color:        Optional background color for the annotation.
        :param border_color:            Optional border color for the annotation.
        :param border_dash_pattern:     Dash pattern used for the annotation's border lines.
        :param border_dash_phase:       Phase offset for the dash pattern in the borders.
        :param border_width_bottom:     Width of the bottom border of the annotation.
        :param border_width_left:       Width of the left border of the annotation.
        :param border_width_right:      Width of the right border of the annotation.
        :param border_width_top:        Width of the top border of the annotation.
        :param horizontal_alignment:     Horizontal alignment of the annotation (default is LEFT).
        :param margin_bottom:           Space between the annotation and the element below it.
        :param margin_left:             Space between the annotation and the left page margin.
        :param margin_right:            Space between the annotation and the right page margin.
        :param margin_top:              Space between the annotation and the element above it.
        :param padding_bottom:          Padding inside the annotation at the bottom.
        :param padding_left:            Padding inside the annotation on the left side.
        :param padding_right:           Padding inside the annotation on the right side.
        :param padding_top:             Padding inside the annotation at the top.
        :param vertical_alignment:       Vertical alignment of the annotation (default is TOP).
        """
        ...
    
    def paint(self, available_space: typing.Tuple[int, int, int, int], page: Page) -> None:
        """
        Render the layout element onto the provided page using the available space.

        This function renders the layout element within the given available space on the specified page.

        :param available_space: A tuple representing the available space (left, top, right, bottom).
        :param page:            The Page object on which to render the LayoutElement.
        :return:                None.
        """
        ...
    


