"""
This type stub file was generated by pyright.
"""

import enum
import typing
from borb.pdf.color.color import Color
from borb.pdf.layout_element.annotation.annotation import Annotation
from borb.pdf.layout_element.layout_element import LayoutElement

"""
Represents a rubber stamp annotation, which displays text or graphics resembling a stamped image.

A rubber stamp annotation (PDF 1.3) visually simulates the appearance of being stamped on the
page with a rubber stamp. When opened, it displays a pop-up window containing the text of the
associated note.

Table 181 shows the annotation dictionary entries specific to this type of annotation.
"""
class RubberStampAnnotation(Annotation):
    """
    Represents a rubber stamp annotation, which displays text or graphics resembling a stamped image.

    A rubber stamp annotation (PDF 1.3) visually simulates the appearance of being stamped on the
    page with a rubber stamp. When opened, it displays a pop-up window containing the text of the
    associated note.

    Table 181 shows the annotation dictionary entries specific to this type of annotation.
    """
    class RubberStampAnnotationType(enum.Enum):
        """
        Defines the names of icons used to display rubber stamp annotations.

        This enumeration specifies the predefined icon appearances for rubber stamp annotations.
        Conforming readers must provide support for at least the following standard names:

        - Approved
        - Experimental
        - NotApproved
        - AsIs
        - Expired
        - Sold
        - Departmental
        - NotForPublicRelease
        - Confidential
        - Final
        - ForComment
        - TopSecret
        - Draft
        - ForPublicRelease

        Additional names may also be supported. The default value is "Draft".

        If present, the annotation dictionary’s AP entry takes precedence over the Name entry;
        refer to Table 168 and section 12.5.5, “Appearance Streams,” for further details.
        """
        APPROVED = ...
        AS_IS = ...
        CONFIDENTIAL = ...
        DEPARTMENTAL = ...
        DRAFT = ...
        EXPERIMENTAL = ...
        EXPIRED = ...
        FINAL = ...
        FOR_COMMENT = ...
        FOR_PUBLIC_RELEASE = ...
        NOT_APPROVED = ...
        NOT_FOR_PUBLIC_RELEASE = ...
        SOLD = ...
        TOP_SECRET = ...
    
    
    def __init__(self, background_color: typing.Optional[Color] = ..., border_color: typing.Optional[Color] = ..., border_dash_pattern: typing.List[int] = ..., border_dash_phase: int = ..., border_width_bottom: int = ..., border_width_left: int = ..., border_width_right: int = ..., border_width_top: int = ..., contents: typing.Optional[str] = ..., horizontal_alignment: LayoutElement.HorizontalAlignment = ..., margin_bottom: int = ..., margin_left: int = ..., margin_right: int = ..., margin_top: int = ..., padding_bottom: int = ..., padding_left: int = ..., padding_right: int = ..., padding_top: int = ..., rubber_stamp_annotation_type: RubberStampAnnotationType = ..., size: typing.Tuple[int, int] = ..., vertical_alignment: LayoutElement.VerticalAlignment = ...) -> None:
        """
        Initialize a new `RubberStampAnnotation` object for rendering a stamp annotation in a PDF.

        This constructor allows customization of various layout and style properties for
        the stamp annotation, such as background color, borders, size, contents, and alignment.
        These properties define the appearance and positioning of the annotation within the PDF page.

        :param background_color:           Optional background color for the stamp annotation.
        :param border_color:               Optional border color for the annotation container.
        :param border_dash_pattern:        Dash pattern used for the annotation border lines.
        :param border_dash_phase:          Phase offset for the dash pattern in the annotation borders.
        :param border_width_bottom:        Width of the bottom border of the annotation container.
        :param border_width_left:          Width of the left border of the annotation container.
        :param border_width_right:         Width of the right border of the annotation container.
        :param border_width_top:           Width of the top border of the annotation container.
        :param contents:                   Optional text content of the stamp annotation.
        :param horizontal_alignment:       Horizontal alignment of the annotation (default is LEFT).
        :param padding_bottom:             Padding inside the annotation container at the bottom.
        :param padding_left:               Padding inside the annotation container on the left side.
        :param padding_right:              Padding inside the annotation container on the right side.
        :param padding_top:                Padding inside the annotation container at the top.
        :param rubber_stamp_annotation_type: Type of rubber stamp annotation (default is DRAFT).
        :param size:                       Tuple representing the width and height of the annotation.
        :param vertical_alignment:         Vertical alignment of the annotation (default is TOP).
        """
        ...
    


