"""
This type stub file was generated by pyright.
"""

import pathlib
import typing
from borb.pdf.color.color import Color
from borb.pdf.layout_element.annotation.annotation import Annotation
from borb.pdf.layout_element.layout_element import LayoutElement

"""
Represents a sound annotation that embeds an audio file in the PDF document.

Sound annotations (PDF 1.3) associate an audio file with a specific point on the page. When activated,
they allow the user to play the embedded audio content. The annotation can be triggered either by
clicking the annotation icon or through other user interactions. The annotation's location and
appearance on the page are determined by the Rect entry in the annotation dictionary.

The audio is stored as a stream in a format suitable for embedding, such as raw PCM or other supported
audio formats. The annotation's appearance can be customized, and the audio content can be played using
PDF viewers that support this feature.
"""
class SoundAnnotation(Annotation):
    """
    Represents a sound annotation that embeds an audio file in the PDF document.

    Sound annotations (PDF 1.3) associate an audio file with a specific point on the page. When activated,
    they allow the user to play the embedded audio content. The annotation can be triggered either by
    clicking the annotation icon or through other user interactions. The annotation's location and
    appearance on the page are determined by the Rect entry in the annotation dictionary.

    The audio is stored as a stream in a format suitable for embedding, such as raw PCM or other supported
    audio formats. The annotation's appearance can be customized, and the audio content can be played using
    PDF viewers that support this feature.
    """
    def __init__(self, path_to_audio_file: pathlib.Path, background_color: typing.Optional[Color] = ..., border_color: typing.Optional[Color] = ..., border_dash_pattern: typing.List[int] = ..., border_dash_phase: int = ..., border_width_bottom: int = ..., border_width_left: int = ..., border_width_right: int = ..., border_width_top: int = ..., contents: typing.Optional[str] = ..., horizontal_alignment: LayoutElement.HorizontalAlignment = ..., margin_bottom: int = ..., margin_left: int = ..., margin_right: int = ..., margin_top: int = ..., padding_bottom: int = ..., padding_left: int = ..., padding_right: int = ..., padding_top: int = ..., size: typing.Tuple[int, int] = ..., vertical_alignment: LayoutElement.VerticalAlignment = ...) -> None:
        """
        Initialize a sound annotation that embeds an audio file and links to a destination.

        This constructor sets up a sound annotation, allowing users to attach an audio file to a specific
        location in the document. The sound can be triggered by user interaction with the annotation, such
        as clicking the annotation icon. The annotation’s appearance, including dimensions and visual properties
        (e.g., background and border colors), can be customized.

        The embedded audio is stored in a suitable format for PDF, such as raw PCM or other compatible audio types.

        :param path_to_audio_file:      the pathlib.Path pointing to the audio file
        :param background_color:        Optional background color for the annotation.
        :param border_color:            Optional border color for the annotation.
        :param border_dash_pattern:     Dash pattern used for the annotation's border lines.
        :param border_dash_phase:       Phase offset for the dash pattern in the borders.
        :param border_width_bottom:     Width of the bottom border of the annotation.
        :param border_width_left:       Width of the left border of the annotation.
        :param border_width_right:      Width of the right border of the annotation.
        :param border_width_top:        Width of the top border of the annotation.
        :param horizontal_alignment:     Horizontal alignment of the annotation (default is LEFT).
        :param margin_bottom:           Space between the annotation and the element below it.
        :param margin_left:             Space between the annotation and the left page margin.
        :param margin_right:            Space between the annotation and the right page margin.
        :param margin_top:              Space between the annotation and the element above it.
        :param padding_bottom:          Padding inside the annotation at the bottom.
        :param padding_left:            Padding inside the annotation on the left side.
        :param padding_right:           Padding inside the annotation on the right side.
        :param padding_top:             Padding inside the annotation at the top.
        :param vertical_alignment:       Vertical alignment of the annotation (default is TOP).
        """
        ...
    


