"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.color.color import Color
from borb.pdf.layout_element.annotation.annotation import Annotation
from borb.pdf.layout_element.layout_element import LayoutElement

"""
Represents a square annotation that displays a rectangle on the page.

Square annotations (PDF 1.3) display a rectangle on the page. When opened, they shall
show a pop-up window containing the text of the associated note. The rectangle shall be
inscribed within the annotation rectangle defined by the annotation dictionary’s Rect entry
(see Table 168).

Circle annotations display an ellipse, following similar behavior as square annotations.
"""
class SquareAnnotation(Annotation):
    """
    Represents a square annotation that displays a rectangle on the page.

    Square annotations (PDF 1.3) display a rectangle on the page. When opened, they shall
    show a pop-up window containing the text of the associated note. The rectangle shall be
    inscribed within the annotation rectangle defined by the annotation dictionary’s Rect entry
    (see Table 168).

    Circle annotations display an ellipse, following similar behavior as square annotations.
    """
    def __init__(self, background_color: typing.Optional[Color] = ..., border_color: typing.Optional[Color] = ..., border_dash_pattern: typing.List[int] = ..., border_dash_phase: int = ..., border_width_bottom: int = ..., border_width_left: int = ..., border_width_right: int = ..., border_width_top: int = ..., contents: typing.Optional[str] = ..., fill_color: typing.Optional[Color] = ..., horizontal_alignment: LayoutElement.HorizontalAlignment = ..., margin_bottom: int = ..., margin_left: int = ..., margin_right: int = ..., margin_top: int = ..., padding_bottom: int = ..., padding_left: int = ..., padding_right: int = ..., padding_top: int = ..., size: typing.Tuple[int, int] = ..., stroke_color: typing.Optional[Color] = ..., vertical_alignment: LayoutElement.VerticalAlignment = ...) -> None:
        """
        Initialize a new `SquareAnnotation` object for rendering a square annotation in a PDF.

        This constructor allows customization of various layout and style properties for
        the square annotation, such as background color, border, fill color, size,
        contents, and alignment. These properties define the appearance and positioning of
        the square annotation within the PDF page.

        :param background_color:         Optional background color for the square annotation.
        :param border_color:             Optional border color for the annotation container.
        :param border_dash_pattern:      Dash pattern used for the annotation border lines.
        :param border_dash_phase:        Phase offset for the dash pattern in the annotation borders.
        :param border_width_bottom:      Width of the bottom border of the annotation container.
        :param border_width_left:        Width of the left border of the annotation container.
        :param border_width_right:       Width of the right border of the annotation container.
        :param border_width_top:         Width of the top border of the annotation container.
        :param contents:                 Optional text content for the annotation.
        :param fill_color:               Optional fill color for the square annotation.
        :param horizontal_alignment:     Horizontal alignment of the annotation (default is LEFT).
        :param padding_bottom:           Padding inside the annotation container at the bottom.
        :param padding_left:             Padding inside the annotation container on the left side.
        :param padding_right:            Padding inside the annotation container on the right side.
        :param padding_top:              Padding inside the annotation container at the top.
        :param size:                     Tuple representing the width and height of the annotation.
        :param stroke_color:             Color of the square's stroke (default is BLACK).
        :param vertical_alignment:       Vertical alignment of the annotation (default is TOP).
        """
        ...
    


