"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.color.color import Color
from borb.pdf.layout_element.annotation.annotation import Annotation
from borb.pdf.layout_element.layout_element import LayoutElement

"""
Represents a text annotation, often referred to as a "sticky note" in the PDF document.

When closed, the annotation appears as an icon; when opened, it displays a pop-up window containing the
text of the note. The font and size of the text are determined by the conforming reader.

Text annotations do not scale or rotate with the page; they behave as if the NoZoom and NoRotate
annotation flags (see Table 165) are always set.

Table 172 shows the annotation dictionary entries specific to this type of annotation.
"""
class TextAnnotation(Annotation):
    """
    Represents a text annotation, often referred to as a "sticky note" in the PDF document.

    When closed, the annotation appears as an icon; when opened, it displays a pop-up window containing the
    text of the note. The font and size of the text are determined by the conforming reader.

    Text annotations do not scale or rotate with the page; they behave as if the NoZoom and NoRotate
    annotation flags (see Table 165) are always set.

    Table 172 shows the annotation dictionary entries specific to this type of annotation.
    """
    def __init__(self, background_color: typing.Optional[Color] = ..., border_color: typing.Optional[Color] = ..., border_dash_pattern: typing.List[int] = ..., border_dash_phase: int = ..., border_width_bottom: int = ..., border_width_left: int = ..., border_width_right: int = ..., border_width_top: int = ..., contents: typing.Optional[str] = ..., horizontal_alignment: LayoutElement.HorizontalAlignment = ..., margin_bottom: int = ..., margin_left: int = ..., margin_right: int = ..., margin_top: int = ..., padding_bottom: int = ..., padding_left: int = ..., padding_right: int = ..., padding_top: int = ..., size: typing.Tuple[int, int] = ..., vertical_alignment: LayoutElement.VerticalAlignment = ...) -> None:
        """
        Initialize a TextAnnotation object to represent a text annotation in a PDF document.

        This constructor allows for customization of appearance, layout, and content for the text
        annotation, including background color, border style, alignment, margins, padding, and size.

        :param background_color: Optional; background color of the annotation.
        :param border_color: Optional; color of the annotation's border.
        :param border_dash_pattern: Dash pattern for the border as a list of integers.
        :param border_dash_phase: Starting point for the dash pattern along the border.
        :param border_width_bottom: Bottom border width.
        :param border_width_left: Left border width.
        :param border_width_right: Right border width.
        :param border_width_top: Top border width.
        :param contents: Optional; text content displayed within the annotation.
        :param horizontal_alignment: Alignment of content within the annotation horizontally.
        :param margin_bottom: Bottom margin for spacing around the annotation.
        :param margin_left: Left margin for spacing around the annotation.
        :param margin_right: Right margin for spacing around the annotation.
        :param margin_top: Top margin for spacing around the annotation.
        :param padding_bottom: Bottom padding within the annotation.
        :param padding_left: Left padding within the annotation.
        :param padding_right: Right padding within the annotation.
        :param padding_top: Top padding within the annotation.
        :param size: Tuple specifying width and height of the annotation.
        :param vertical_alignment: Alignment of content within the annotation vertically.
        """
        ...
    


