"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.toolkit.event import Event
from borb.pdf.toolkit.sink.sink import Sink

"""
A filter class for extracting text content from PDF pages.

The `GetText` class processes PDF page content streams and collects the text content
rendered on each page. It stores the text events, grouped by page number, and allows
for easy retrieval of the extracted text content on a per-page basis. This class is
useful for applications that need to analyze or extract text from specific pages of a PDF.
"""
class GetText(Sink):
    """
    A filter class for extracting text content from PDF pages.

    The `GetText` class processes PDF page content streams and collects the text content
    rendered on each page. It stores the text events, grouped by page number, and allows
    for easy retrieval of the extracted text content on a per-page basis. This class is
    useful for applications that need to analyze or extract text from specific pages of a PDF.
    """
    def __init__(self) -> None:
        """
        Initialize the GetText filter.

        This constructor sets up the necessary structures for extracting and storing
        text content from each page of a PDF. It prepares the filter to capture
        text-related events during the PDF processing pipeline, allowing for text
        extraction based on the processed content streams.
        """
        ...
    
    def get_output(self) -> typing.Any:
        """
        Retrieve the aggregated results from the pipeline.

        This method should be overridden by subclasses to provide the specific output
        collected by the `Sink`. By default, it returns `None`, indicating that no
        aggregation or processing has been implemented.

        :return: The aggregated output from the pipeline, or `None` if not implemented.
        """
        ...
    
    def process(self, event: Event) -> None:
        """
        Process the given event.

        This base implementation is a no-op. Subclasses should override this method
        to provide specific processing logic.

        :param event: The event object to process.
        """
        ...
    


