"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.toolkit.event import Event
from borb.pdf.toolkit.sink.sink import Sink

"""
A sink class that captures image events from the PDF content pipeline.

The `GetImages` class sits at the end of the PDF processing pipeline, serving as a sink to
capture and store any image events that pass through the pipeline. It collects image-related
data, such as image objects, their positions, and dimensions, enabling further processing or
extraction of image content from the PDF document.

This class does not alter the content stream but rather listens for image-related events
and stores them for future use or analysis.
"""
class GetImages(Sink):
    """
    A sink class that captures image events from the PDF content pipeline.

    The `GetImages` class sits at the end of the PDF processing pipeline, serving as a sink to
    capture and store any image events that pass through the pipeline. It collects image-related
    data, such as image objects, their positions, and dimensions, enabling further processing or
    extraction of image content from the PDF document.

    This class does not alter the content stream but rather listens for image-related events
    and stores them for future use or analysis.
    """
    def __init__(self) -> None:
        """
        Initialize a `GetImages` instance.

        The `GetImages` class acts as a sink in the PDF processing pipeline, collecting and
        organizing image-related events (`ImageEvent`) from a PDF document. This constructor
        initializes the internal data structure used to store these events, grouped by the page
        on which they occur.
        """
        ...
    
    def get_output(self) -> typing.Any:
        """
        Retrieve the aggregated results from the pipeline.

        This method should be overridden by subclasses to provide the specific output
        collected by the `Sink`. By default, it returns `None`, indicating that no
        aggregation or processing has been implemented.

        :return: The aggregated output from the pipeline, or `None` if not implemented.
        """
        ...
    
    def process(self, event: Event) -> None:
        """
        Process the given event.

        This base implementation is a no-op. Subclasses should override this method
        to provide specific processing logic.

        :param event: The event object to process.
        """
        ...
    


