"""
This type stub file was generated by pyright.
"""

import functools
import typing
from borb.pdf.color.color import Color
from borb.pdf.layout_element.layout_element import LayoutElement
from borb.pdf.page import Page

"""
Represents a progress bar element for visualizing task completion within a PDF document.

This class is designed to display a horizontal progress bar that reflects the completion
status of a task or process within a PDF layout. The progress bar can be customized for
appearance, size, and percentage completion.
"""
class ProgressBar(LayoutElement):
    """
    Represents a progress bar element for visualizing task completion within a PDF document.

    This class is designed to display a horizontal progress bar that reflects the completion
    status of a task or process within a PDF layout. The progress bar can be customized for
    appearance, size, and percentage completion.
    """
    def __init__(self, value: int, max_value: int = ..., size: typing.Tuple[int, int] = ..., stroke_color: Color = ..., fill_color: Color = ..., background_color: typing.Optional[Color] = ..., border_color: typing.Optional[Color] = ..., border_dash_pattern: typing.List[int] = ..., border_dash_phase: int = ..., border_width_bottom: int = ..., border_width_left: int = ..., border_width_right: int = ..., border_width_top: int = ..., horizontal_alignment: LayoutElement.HorizontalAlignment = ..., margin_bottom: int = ..., margin_left: int = ..., margin_right: int = ..., margin_top: int = ..., padding_bottom: int = ..., padding_left: int = ..., padding_right: int = ..., padding_top: int = ..., vertical_alignment: LayoutElement.VerticalAlignment = ...) -> None:
        """
        Initialize a ProgressBar object with customizable attributes.

        The `ProgressBar` class represents a visual progress bar, which can be customized in terms of value,
        size, color, alignment, and margins.
        It supports defining the progress level (`value`),
        appearance (such as fill color, stroke color, and border settings),
        and positioning (via padding, margin, and alignment).

        :param value:               The current progress value (e.g., 40 out of 100).
        :param max_value:           The maximum value of the progress bar, default is 100.
        :param size:                A tuple representing the width and height of the progress bar, default is (121, 15).
        :param stroke_color:        The color of the bar's stroke or outline, default is `X11Color.LIGHT_STEEL_BLUE`.
        :param fill_color:          The color used to fill the progress bar, default is `X11Color.GAINSBORO`.
        :param background_color:    Optional background color for the progress bar, defaults to None.
        :param border_color:        Optional border color for the progress bar, defaults to None.
        :param border_dash_pattern: A list specifying dash patterns for the border, default is an empty list (no dashes).
        :param border_dash_phase:   An integer representing the phase of the border dash pattern, default is 0.
        :param border_width_bottom: The bottom border width, default is 0.
        :param border_width_left:   The left border width, default is 0.
        :param border_width_right:  The right border width, default is 0.
        :param border_width_top:    The top border width, default is 0.
        :param horizontal_alignment: Horizontal alignment of the progress bar, default is `LayoutElement.HorizontalAlignment.LEFT`.
        :param margin_bottom:       The bottom margin in points, default is 0.
        :param margin_left:         The left margin in points, default is 0.
        :param margin_right:        The right margin in points, default is 0.
        :param margin_top:          The top margin in points, default is 0.
        :param padding_bottom:      The bottom padding in points, default is 0.
        :param padding_left:        The left padding in points, default is 0.
        :param padding_right:       The right padding in points, default is 0.
        :param padding_top:         The top padding in points, default is 0.
        :param vertical_alignment:  Vertical alignment of the progress bar, default is `LayoutElement.VerticalAlignment.TOP`.
        """
        ...
    
    @functools.cache
    def get_size(self, available_space: typing.Tuple[int, int]) -> typing.Tuple[int, int]:
        """
        Calculate and return the size of the layout element based on available space.

        This function uses the available space to compute the size (width, height)
        of the layout element in points.

        :param available_space: Tuple representing the available space (width, height).
        :return:                Tuple containing the size (width, height) in points.
        """
        ...
    
    def paint(self, available_space: typing.Tuple[int, int, int, int], page: Page) -> None:
        """
        Render the layout element onto the provided page using the available space.

        This function renders the layout element within the given available space on the specified page.

        :param available_space: A tuple representing the available space (left, top, right, bottom).
        :param page:            The Page object on which to render the LayoutElement.
        :return:                None.
        """
        ...
    


