"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.color.color import Color
from borb.pdf.layout_element.layout_element import LayoutElement
from borb.pdf.layout_element.progress_bar.progress_bar import ProgressBar

"""
Represents a progress bar element for visualizing task completion within a PDF document.

This class is designed to display a horizontal progress bar that reflects the completion
status of a task or process within a PDF layout. The progress bar can be customized for
appearance, size, and percentage completion.
"""
class ProgressSquare(ProgressBar):
    """
    Represents a progress bar element for visualizing task completion within a PDF document.

    This class is designed to display a horizontal progress bar that reflects the completion
    status of a task or process within a PDF layout. The progress bar can be customized for
    appearance, size, and percentage completion.
    """
    def __init__(self, value: int, background_color: typing.Optional[Color] = ..., border_color: typing.Optional[Color] = ..., border_dash_pattern: typing.List[int] = ..., border_dash_phase: int = ..., border_width_bottom: int = ..., border_width_left: int = ..., border_width_right: int = ..., border_width_top: int = ..., fill_color: Color = ..., horizontal_alignment: LayoutElement.HorizontalAlignment = ..., margin_bottom: int = ..., margin_left: int = ..., margin_right: int = ..., margin_top: int = ..., max_value: int = ..., padding_bottom: int = ..., padding_left: int = ..., padding_right: int = ..., padding_top: int = ..., stroke_color: Color = ..., vertical_alignment: LayoutElement.VerticalAlignment = ..., width: int = ...) -> None:
        """
        Initialize a ProgressBar object with customizable attributes.

        The `ProgressBar` class represents a visual progress bar, which can be customized in terms of value,
        size, color, alignment, and margins.
        It supports defining the progress level (`value`),
        appearance (such as fill color, stroke color, and border settings),
        and positioning (via padding, margin, and alignment).

        :param value:               The current progress value (e.g., 40 out of 100).
        :param max_value:           The maximum value of the progress bar, default is 100.
        :param stroke_color:        The color of the bar's stroke or outline, default is `X11Color.LIGHT_STEEL_BLUE`.
        :param fill_color:          The color used to fill the progress bar, default is `X11Color.GAINSBORO`.
        :param background_color:    Optional background color for the progress bar, defaults to None.
        :param border_color:        Optional border color for the progress bar, defaults to None.
        :param border_dash_pattern: A list specifying dash patterns for the border, default is an empty list (no dashes).
        :param border_dash_phase:   An integer representing the phase of the border dash pattern, default is 0.
        :param border_width_bottom: The bottom border width, default is 0.
        :param border_width_left:   The left border width, default is 0.
        :param border_width_right:  The right border width, default is 0.
        :param border_width_top:    The top border width, default is 0.
        :param horizontal_alignment: Horizontal alignment of the progress bar, default is `LayoutElement.HorizontalAlignment.LEFT`.
        :param margin_bottom:       The bottom margin in points, default is 0.
        :param margin_left:         The left margin in points, default is 0.
        :param margin_right:        The right margin in points, default is 0.
        :param margin_top:          The top margin in points, default is 0.
        :param padding_bottom:      The bottom padding in points, default is 0.
        :param padding_left:        The left padding in points, default is 0.
        :param padding_right:       The right padding in points, default is 0.
        :param padding_top:         The top padding in points, default is 0.
        :param vertical_alignment:  Vertical alignment of the progress bar, default is `LayoutElement.VerticalAlignment.TOP`.
        """
        ...
    


