"""
This type stub file was generated by pyright.
"""

import datetime
import typing
from borb.pdf.conformance import Conformance
from borb.pdf.page import Page

"""
Represents a PDF document, providing functionality to create, manipulate, and export PDF files.

The Document class allows for adding and organizing pages, embedding various types of content
such as text, images, and tables, and managing features like metadata, encryption, and annotations.
It serves as the main structure for building and editing PDF documents, offering control over
the document's layout and content.

Instances of this class can be serialized to standard PDF format for viewing, sharing, or printing.
"""
class Document(dict):
    """
    Represents a PDF document with functionality to create, manipulate, and export PDF files.

    The Document class allows for adding and organizing pages, embedding various types
    of content such as text, images, and tables, and managing features like metadata,
    encryption, and annotations. It serves as the primary structure for building and
    editing PDF documents, offering control over the document's layout and content.

    Instances of this class can be serialized to standard PDF format for viewing,
    sharing, or printing.
    """
    def __init__(self, conformance: typing.Optional[Conformance] = ..., on_non_conformance_print_warning: bool = ..., on_non_conformance_throw_assert: bool = ...) -> None:
        """
        Initialize a new instance of the `Document` class.

        This constructor sets up the document with an optional conformance level.
        The conformance level defines the PDF compliance standards (such as PDF/A)
        the document is intended to meet. If no conformance level is specified,
        the document will not be bound to any particular compliance level upon creation.

        :param conformance: An optional `Conformance` value indicating the
                            desired compliance standard for the document (e.g.,
                            PDF/A-1, PDF/A-2, etc.). If `None`, no specific
                            conformance is set at document creation.
        """
        ...
    
    def append_document(self, other: Document) -> Document:
        """
        Append all pages of another Document to this Document.

        This method initializes the document structure (if needed) and sequentially
        appends each page from the given `other` Document to the current Document.

        :param other:   The Document whose pages should be appended.
        :returns:       The modified Document instance with the appended pages.
        """
        ...
    
    def append_page(self, page: Page) -> Document:
        """
        Append a Page object to the document.

        This method adds the specified page to the end of the document's list of pages. It modifies
        the document in place and returns the updated Document object, allowing for method chaining.

        :param page:    the Page to append
        :return:        self
        """
        ...
    
    def get_author(self) -> typing.Optional[str]:
        """
        Retrieve the author information from the PDF document's metadata, if available.

        This method accesses the "Trailer" dictionary of the PDF, navigating to the "Info"
        dictionary to extract the "Author" entry. The author field typically provides the
        name of the individual or organization that created the document.

        :return: A string representing the author of the document, or `None` if the author
                 information is not available.
        """
        ...
    
    def get_conformance_at_create(self) -> typing.Optional[Conformance]:
        """
        Retrieve the conformance set when the document was created.

        This method returns the conformance that was assigned at the time of document creation.
        This may differ from the conformance upon reading the document.

        :return: The `Conformance` set at creation, or `None` if not specified.
        """
        ...
    
    def get_creation_date(self) -> typing.Optional[datetime.datetime]:
        """
        Retrieve the creation date of the PDF document, if available.

        This method accesses the PDF's "Trailer" dictionary, then navigates to the "Info"
        dictionary to retrieve the "CreationDate" entry. If a creation date is found, it is
        parsed from its expected PDF date format "D:%Y%m%d%H%M%S+00'00'" into a Python
        `datetime` object. If the creation date is missing or cannot be parsed, `None` is returned.

        :return: A `datetime` object representing the document's creation date, or `None`
                 if the creation date is not available or cannot be parsed.
        """
        ...
    
    def get_keywords(self) -> typing.Optional[str]:
        """
        Retrieve the keywords metadata from the PDF document, if available.

        This method accesses the "Trailer" dictionary of the PDF, navigating to the "Info"
        dictionary to extract the "Keywords" entry. The keywords field often contains a
        list of terms or phrases describing the document's content, separated by commas
        or semicolons, intended to aid in document indexing and searchability.

        :return: A string representing the document's keywords, or `None` if no keywords
                 metadata is present.
        """
        ...
    
    def get_modification_date(self) -> typing.Optional[datetime.datetime]:
        """
        Retrieve the modification date of the PDF document, if available.

        This method accesses the PDF's "Trailer" dictionary, then navigates to the "Info"
        dictionary to retrieve the "ModDate" entry. If a modification date is found, it is
        parsed from its expected PDF date format "D:%Y%m%d%H%M%S+00'00'" into a Python
        `datetime` object. If the creation date is missing or cannot be parsed, `None` is returned.

        :return: A `datetime` object representing the document's modification date, or `None`
                 if the modification date is not available or cannot be parsed.
        """
        ...
    
    def get_number_of_pages(self) -> int:
        """
        Retrieve the number of pages in the PDF document.

        This method accesses the "Trailer" dictionary, navigating through the "Root" dictionary
        to locate the "Pages" dictionary and retrieve the "Count" value, which indicates the total
        number of pages in the document. If this information is unavailable, the method returns 0.

        :return: An integer representing the number of pages in the PDF. Returns 0 if
                 the page count is not specified.
        """
        ...
    
    def get_page(self, index: int) -> Page:
        """
        Retrieve the Page object at the specified index.

        This method returns the Page object located at the given zero-based index in the document's
        list of pages. If the index is out of range, it raises an IndexError.

        :param index:   the index
        :return:        self
        """
        ...
    
    def get_producer(self) -> typing.Optional[str]:
        """
        Retrieve the producer information from the PDF document's metadata, if available.

        This method accesses the PDF's "Trailer" dictionary, then navigates to the "Info"
        dictionary to retrieve the "Producer" entry. The producer field generally specifies
        the software or library used to create the PDF document.

        :return: A string representing the producer information, or `None` if the producer
                 information is not available.
        """
        ...
    
    def get_subject(self) -> typing.Optional[str]:
        """
        Retrieve the subject information from the PDF document's metadata, if available.

        This method accesses the "Trailer" dictionary of the PDF, navigating to the "Info"
        dictionary to extract the "Subject" entry. The subject field typically provides a brief
        description or categorization of the document's content.

        :return: A string representing the subject of the document, or `None` if the subject
                 information is not available.
        """
        ...
    
    def get_title(self) -> typing.Optional[str]:
        """
        Retrieve the title information from the PDF document's metadata, if available.

        This method accesses the PDF's "Trailer" dictionary, then navigates to the "Info"
        dictionary to retrieve the "Title" entry. The title field generally provides a
        short description or title for the PDF document.

        :return: A string representing the title of the document, or `None` if the title
                 information is not available.
        """
        ...
    
    def insert_page(self, page: Page, index: int = ...) -> Document:
        """
        Insert a Page object into the document at the specified index.

        This method inserts the given page at the specified position in the document's list of pages.
        If no index is provided or if the index is -1, the page is appended to the end of the document.
        It returns the updated Document object, allowing for method chaining.

        :param page:    the Page to insert
        :param index:   the index at which to insert the Page
        :return:        self
        """
        ...
    
    def pop_page(self, index: int) -> Document:
        """
        Remove and return the Page object at the specified index.

        This method removes the page located at the given zero-based index from the document's
        list of pages. The document is modified in place, and the updated Document object
        is returned for method chaining. If the index is out of range, it raises an IndexError.

        :param index:   the index
        :return:        self
        """
        ...
    


