"""
This type stub file was generated by pyright.
"""

import typing

"""
The `Page` class inherits from `dict` and represents a page in a PDF document.

This class stores various elements and properties associated with the page, such as
text, images, and layout information. It provides a structured way to manage the
content and metadata of a page within the PDF.
"""
class Page(dict):
    """
    The `Page` class inherits from `dict` and represents a page in a PDF document.

    This class stores various elements and properties associated with the page, such as
    text, images, and layout information. It provides a structured way to manage the
    content and metadata of a page within the PDF.
    """
    def __init__(self, height_in_points: int = ..., width_in_points: int = ...) -> None:
        """
        Initialize a new PDF page object with specified dimensions.

        The `Page` class represents a single page in a PDF document, defined by its width and height in points.
        This constructor allows the creation of a page with customizable dimensions,
        typically used for setting up different page sizes such as A4 or letter.

        :param height_in_points:    The height of the page in points. Default is 842 points (A4 height).
        :param width_in_points:     The width of the page in points. Default is 595 points (A4 width).
        """
        ...
    
    def get_document(self) -> typing.Optional[Document]:
        """
        Retrieve the `Document` object to which this `Page` belongs.

        This method returns the `Document` that the current `Page` is part of. If the page
        has not yet been added to a document, it returns `None`. This can be useful when
        working with standalone `Page` objects or when you need to reference the parent
        `Document`.

        :return:    The `Document` object to which this `Page` belongs,
                    or `None` if the `Page` is not part of a `Document`.
        """
        ...
    
    def get_size(self) -> typing.Tuple[int, int]:
        """
        Return the dimensions of the page in points.

        This method typically represents the width and height of the page. The size is determined
        based on the page's content or metadata and helps in understanding how the content fits
        within the page boundaries.

        :return: The size of the page as a tuple of (width, height) in points.
        """
        ...
    
    def rotate_left(self) -> Page:
        """
        Rotate the entire page content by 90 degrees to the left (counterclockwise).

        This method effectively changes the orientation of the page, which is useful for
        adjusting the layout when the page has been scanned or created in the wrong orientation.

        :return: Self, with the updated rotation applied.
        """
        ...
    
    def rotate_right(self) -> Page:
        """
        Rotate the entire page content by 90 degrees to the right (counterclockwise).

        This method effectively changes the orientation of the page, which is useful for
        adjusting the layout when the page has been scanned or created in the wrong orientation.

        :return: Self, with the updated rotation applied.
        """
        ...
    
    def uses_color_images(self) -> bool:
        """
        Determine if the PDF uses color images.

        The PDF operators used in content streams are grouped into categories of related
        operators called procedure sets (see Table 314). Each procedure set corresponds
        to a named resource that contains the implementations of the operators in that
        procedure set. The ProcSet entry in a content stream’s resource dictionary (see
        7.8.3, “Resource Dictionaries”) holds an array consisting of the names of the
        procedure sets used in that content stream.

        This method checks whether the PDF uses operators from the "ImageC" procedure set.

        :return: True if the page uses color images, False otherwise.
        """
        ...
    
    def uses_grayscale_images(self) -> bool:
        """
        Determine if the PDF uses grayscale images.

        The PDF operators used in content streams are grouped into categories of related
        operators called procedure sets (see Table 314). Each procedure set corresponds
        to a named resource that contains the implementations of the operators in that
        procedure set. The ProcSet entry in a content stream’s resource dictionary (see
        7.8.3, “Resource Dictionaries”) holds an array consisting of the names of the
        procedure sets used in that content stream.

        This method checks whether the PDF uses operators from the "ImageB" procedure set.

        :return: True if the page uses grayscale images, False otherwise.
        """
        ...
    
    def uses_indexed_images(self) -> bool:
        """
        Determine if the PDF uses indexed images.

        The PDF operators used in content streams are grouped into categories of related
        operators called procedure sets (see Table 314). Each procedure set corresponds
        to a named resource that contains the implementations of the operators in that
        procedure set. The ProcSet entry in a content stream’s resource dictionary (see
        7.8.3, “Resource Dictionaries”) holds an array consisting of the names of the
        procedure sets used in that content stream.

        This method checks whether the PDF uses operators from the "ImageI" procedure set.

        :return: True if the page uses indexed images, False otherwise.
        """
        ...
    
    def uses_painting_and_graphics_state(self) -> bool:
        """
        Check if the PDF uses operators from the painting and graphics state procedure set.

        PDF operators used in content streams are grouped into categories called procedure
        sets (see Table 314). Each procedure set corresponds to a named resource containing
        the implementations of the operators in that procedure set. The ProcSet entry in a
        content stream’s resource dictionary (see 7.8.3, “Resource Dictionaries”) holds
        an array of the names of the procedure sets used in that content stream.

        This method determines whether the PDF utilizes operators from the "PDF" procedure set.

        :return: True if the page uses operators from the "PDF" procedure set, False otherwise.
        """
        ...
    
    def uses_text(self) -> bool:
        """
        Check if the PDF uses text operators.

        PDF operators used in content streams are grouped into categories called procedure
        sets (see Table 314). Each procedure set corresponds to a named resource that
        contains the implementations of the operators in that procedure set. The ProcSet
        entry in a content stream’s resource dictionary (see 7.8.3, “Resource Dictionaries”)
        holds an array of the names of the procedure sets used in that content stream.

        This method determines whether the PDF utilizes operators from the "Text"
        procedure set.

        :return: True if the page uses operators from the "Text" procedure set, False otherwise.
        """
        ...
    


