"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.layout_element.layout_element import LayoutElement
from borb.pdf.layout_element.table.table import Table

"""
Utility class for creating and managing tables in PDF documents.

The `TableUtil` class provides helper methods for generating tables from structured data.
It simplifies the process of converting raw tabular data into a table format suitable for use in PDF documents.
This class allows for customization of table appearance, such as font size,
padding, alignment, and the designation of headers.
"""
class TableUtil:
    """
    Utility class for creating and managing tables in PDF documents.

    The `TableUtil` class provides helper methods for generating tables from structured data.
    It simplifies the process of converting raw tabular data into a table format suitable for use in PDF documents.
    This class allows for customization of table appearance, such as font size,
    padding, alignment, and the designation of headers.
    """
    @staticmethod
    def from_2d_data(tabular_data: typing.List[typing.List[typing.Any]], fixed_column_width: int = ..., font_size: int = ..., header_col: bool = ..., header_row: bool = ..., horizontal_alignment: LayoutElement.HorizontalAlignment = ..., padding_bottom: int = ..., padding_left: int = ..., padding_right: int = ..., padding_top: int = ..., vertical_alignment: LayoutElement.VerticalAlignment = ...) -> Table:
        """
        Create a `Table` instance from 2D tabular data.

        The `from_2d_data` method is a static method that generates a table from a 2D list of data,
        allowing for customization of font size, alignment, padding,
        and whether the first row or column should be treated as headers.
        This method simplifies the creation of tables for PDF documents
        by converting raw data into a structured table format.

        :param tabular_data:            A 2D list of values where each sublist represents a row of data.
        :param font_size:               The font size for the table text. Default is 12.
        :param header_col:              A boolean indicating if the first column should be treated as a header.
                                        Default is False.
        :param header_row:              A boolean indicating if the first row should be treated as a header.
                                        Default is True.
        :param horizontal_alignment:    Specifies the horizontal alignment of table content.
                                        Can be LEFT, MIDDLE, or RIGHT. Default is LEFT.
        :param padding_bottom:          The amount of padding to apply to the bottom of each cell. Default is 0.
        :param padding_left:            The amount of padding to apply to the left of each cell. Default is 0.
        :param padding_right:           The amount of padding to apply to the right of each cell. Default is 0.
        :param padding_top:             The amount of padding to apply to the top of each cell. Default is 0.
        :param vertical_alignment:      Specifies the vertical alignment of table content.
                                        Can be TOP, MIDDLE, or BOTTOM. Default is TOP.
        :return:                        Self, allowing for method chaining
        """
        ...
    


