"""
This type stub file was generated by pyright.
"""

import functools
import typing
from borb.pdf.color.color import Color
from borb.pdf.layout_element.layout_element import LayoutElement
from borb.pdf.layout_element.shape.shape import Shape
from borb.pdf.page import Page

"""
A generic class representing a map as a drawable shape in a PDF document.

The Map class provides functionality to render geographic regions (such as countries or states) within a PDF.
It retrieves geographic data from a compressed geo-JSON file and allows customization of regions by specifying
fill and stroke colors for each one. The Map class can be specialized to represent different parts of the world,
such as Europe or the entire globe.

Use this class to generate maps, customize region appearances, and integrate geographic shapes into a PDF.
"""
PolygonType: typing.TypeAlias = typing.List[typing.Tuple[float, float]]
PolygonsType: typing.TypeAlias = typing.List[PolygonType]
class Map(Shape):
    """
    A generic class representing a map as a drawable shape in a PDF document.

    The Map class provides functionality to render geographic regions (such as countries or states) within a PDF.
    It retrieves geographic data from a compressed geo-JSON file and allows customization of regions by specifying
    fill and stroke colors for each one. The Map class can be specialized to represent different parts of the world,
    such as Europe or the entire globe.

    Use this class to generate maps, customize region appearances, and integrate geographic shapes into a PDF.
    """
    def __init__(self, geo_json: typing.Dict, background_color: typing.Optional[Color] = ..., border_color: typing.Optional[Color] = ..., border_dash_pattern: typing.List[int] = ..., border_dash_phase: int = ..., border_width_bottom: int = ..., border_width_left: int = ..., border_width_right: int = ..., border_width_top: int = ..., dash_pattern: typing.List[int] = ..., dash_phase: int = ..., fill_color: typing.Optional[Color] = ..., horizontal_alignment: LayoutElement.HorizontalAlignment = ..., line_width: int = ..., margin_bottom: int = ..., margin_left: int = ..., margin_right: int = ..., margin_top: int = ..., padding_bottom: int = ..., padding_left: int = ..., padding_right: int = ..., padding_top: int = ..., stroke_color: typing.Optional[Color] = ..., vertical_alignment: LayoutElement.VerticalAlignment = ...) -> None:
        """
        Initialize a Map object that represents geographical shapes and lines.

        This constructor takes in a GeoJSON dictionary to define the shapes and lines
        to be rendered in the map. It also allows for customization of various
        visual properties, such as colors, borders, and alignment.

        :param geo_json: A dictionary containing GeoJSON data that defines the map's features.
        :param background_color: The background color of the map (default is None).
        :param border_color: The color of the border surrounding the map (default is None).
        :param border_dash_pattern: A list defining the dash pattern for the border (default is an empty list).
        :param border_dash_phase: The phase for the dashed border (default is 0).
        :param border_width_bottom: The width of the bottom border (default is 0).
        :param border_width_left: The width of the left border (default is 0).
        :param border_width_right: The width of the right border (default is 0).
        :param border_width_top: The width of the top border (default is 0).
        :param dash_pattern: A list defining the dash pattern for map features (default is an empty list).
        :param dash_phase: The phase for dashed map features (default is 0).
        :param fill_color: The fill color for map regions (default is None).
        :param horizontal_alignment: The horizontal alignment of the map (default is left).
        :param line_width: The line width for drawing map features (default is 0.1).
        :param margin_bottom: The bottom margin around the map (default is 0).
        :param margin_left: The left margin around the map (default is 0).
        :param margin_right: The right margin around the map (default is 0).
        :param margin_top: The top margin around the map (default is 0).
        :param padding_bottom: The bottom padding inside the map (default is 0).
        :param padding_left: The left padding inside the map (default is 0).
        :param padding_right: The right padding inside the map (default is 0).
        :param padding_top: The top padding inside the map (default is 0).
        :param stroke_color: The stroke color for map features (default is black).
        :param vertical_alignment: The vertical alignment of the map (default is top).
        """
        ...
    
    @functools.cache
    def get_size(self, available_space: typing.Tuple[int, int]) -> typing.Tuple[int, int]:
        """
        Calculate and return the size of the layout element based on available space.

        This function uses the available space to compute the size (width, height)
        of the layout element in points.

        :param available_space: Tuple representing the available space (width, height).
        :return:                Tuple containing the size (width, height) in points.
        """
        ...
    
    def paint(self, available_space: typing.Tuple[int, int, int, int], page: Page) -> None:
        """
        Render the layout element onto the provided page using the available space.

        This function renders the layout element within the given available space on the specified page.

        :param available_space: A tuple representing the available space (left, top, right, bottom).
        :param page:            The Page object on which to render the LayoutElement.
        :return:                None.
        """
        ...
    
    def rotate(self, angle_in_degrees: float) -> Map:
        """
        Rotate the Shape clockwise by the specified angle in degrees.

        :param angle_in_degrees: The angle in degrees by which to rotate the Shape.
        :return: A new Shape object, rotated by the specified angle.
        """
        ...
    
    def scale_by_factor(self, x_factor: float = ..., y_factor: float = ...) -> Shape:
        """
        Scale this Shape by the given factors along the x and y axes.

        This method scales the Shape horizontally by `x_factor` and vertically by `y_factor`.
        The result is a new Shape object that has been resized according to the provided factors.

        :param x_factor: The scale factor for the x-axis.
        :param y_factor: The scale factor for the y-axis.
        :return: A new Shape object scaled by the given factors.
        """
        ...
    
    def scale_to_fit(self, size: typing.Tuple[int, int]) -> Shape:
        """
        Scale this Shape proportionally to fit within the given (width, height) dimensions.

        The aspect ratio is preserved. The resulting Shape will not exceed the specified
        size in either width or height.

        :param size: A tuple (width, height) representing the maximum allowed dimensions.
        :return: A new Shape instance scaled to fit within the given bounds.
        """
        ...
    
    def set_fill_color(self, fill_color: Color, name: str) -> Map:
        """
        Set the fill color for a specific region on the map.

        This method allows you to specify a region by its name and assign a fill color to it.
        For example, you can color France in yellow while keeping the rest of the map in gray.
        This is useful for highlighting specific countries, states, or regions on the map.

        :param fill_color:  The color to fill the specified region with.
        :param name:        The name of the region (e.g., country, state, etc.) to be colored.
        :return:            Returns the modified Map instance, allowing for method chaining.
        """
        ...
    
    def set_stroke_color(self, name: str, stroke_color: Color) -> Map:
        """
        Set the stroke (border) color for a specific region on the map.

        This method allows you to specify a region by its name and assign a stroke color to its border.
        For instance, you can set the border color of France to blue while keeping the rest of the map's
        borders in a different color or unchanged. This is useful for highlighting specific regions.

        :param name:            The name of the region (e.g., country, state, etc.) whose border color will be set.
        :param stroke_color:    The color to apply to the border of the specified region.
        :return:                Returns the modified Map instance, allowing for method chaining.
        """
        ...
    
    def smooth(self) -> Shape:
        """
        Apply Chaikin's algorithm to smooth the polygons within this Shape.

        This method processes each polygon in the current Shape using Chaikin's corner-cutting
        algorithm, which reduces sharp angles and smooths the curves. The result is a new
        Shape object where the polygons have a more refined and smoother appearance.

        :return: A new Shape object with smoothed polygons.
        """
        ...
    


