"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.color.color import Color
from borb.pdf.layout_element.layout_element import LayoutElement
from borb.pdf.layout_element.shape.map import Map

"""
A specialized version of the Map class representing a map of the entire world.

This class extends the generic Map class, providing geographical data for all countries and regions worldwide.
It allows for rendering and customization of global maps, including setting fill and stroke colors for specific
countries or regions.

Use this class to create and manipulate a world map within a PDF document.
"""
class MapOfTheWorld(Map):
    """
    A specialized version of the Map class representing a map of the entire world.

    This class extends the generic Map class, providing geographical data for all countries and regions worldwide.
    It allows for rendering and customization of global maps, including setting fill and stroke colors for specific
    countries or regions.

    Use this class to create and manipulate a world map within a PDF document.
    """
    __MAP_OF_THE_WORLD_BYTES: bytes = ...
    def __init__(self, background_color: typing.Optional[Color] = ..., border_color: typing.Optional[Color] = ..., border_dash_pattern: typing.List[int] = ..., border_dash_phase: int = ..., border_width_bottom: int = ..., border_width_left: int = ..., border_width_right: int = ..., border_width_top: int = ..., dash_pattern: typing.List[int] = ..., dash_phase: int = ..., fill_color: typing.Optional[Color] = ..., horizontal_alignment: LayoutElement.HorizontalAlignment = ..., line_width: int = ..., margin_bottom: int = ..., margin_left: int = ..., margin_right: int = ..., margin_top: int = ..., padding_bottom: int = ..., padding_left: int = ..., padding_right: int = ..., padding_top: int = ..., stroke_color: typing.Optional[Color] = ..., vertical_alignment: LayoutElement.VerticalAlignment = ...) -> None:
        """
        Initialize a map representation for a specified region.

        This constructor sets up the visual properties and layout options for the map, allowing
        customization of colors, borders, alignment, and other attributes.

        :param background_color: Optional background color of the map.
        :param border_color: Optional color for the border of the map.
        :param border_dash_pattern: Optional pattern for dashed borders.
        :param border_dash_phase: Optional phase for the dash pattern.
        :param border_width_bottom: Width of the bottom border.
        :param border_width_left: Width of the left border.
        :param border_width_right: Width of the right border.
        :param border_width_top: Width of the top border.
        :param dash_pattern: Optional pattern for dashed lines within the map.
        :param dash_phase: Optional phase for the dash pattern of lines.
        :param fill_color: Optional fill color for specific regions in the map.
        :param horizontal_alignment: Horizontal alignment of the map.
        :param line_width: Width of the lines drawn on the map.
        :param margin_bottom: Bottom margin around the map.
        :param margin_left: Left margin around the map.
        :param margin_right: Right margin around the map.
        :param margin_top: Top margin around the map.
        :param padding_bottom: Bottom padding inside the map.
        :param padding_left: Left padding inside the map.
        :param padding_right: Right padding inside the map.
        :param padding_top: Top padding inside the map.
        :param stroke_color: Color used for strokes on the map.
        :param vertical_alignment: Vertical alignment of the map.
        """
        ...
    


