"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.color.color import Color
from borb.pdf.layout_element.layout_element import LayoutElement
from borb.pdf.layout_element.meta.layout_element_group import LayoutElementGroup

"""
A group of layout elements arranged in a circular pattern with specified sizes.

This class represents a collection of `LayoutElement` objects, each positioned along
a circular path with predefined sizes. It extends `LayoutElement` and supports rendering
onto a `Page` while respecting layout properties such as alignment, margins, padding, and borders.
"""
class CircularLayoutElementGroup(LayoutElementGroup):
    """
    A group of layout elements arranged in a circular pattern with specified sizes.

    This class represents a collection of `LayoutElement` objects, each positioned along
    a circular path with predefined sizes. It extends `LayoutElement` and supports rendering
    onto a `Page` while respecting layout properties such as alignment, margins, padding, and borders.
    """
    def __init__(self, layout_elements: typing.List[LayoutElement], background_color: typing.Optional[Color] = ..., border_color: typing.Optional[Color] = ..., border_dash_pattern: typing.List[int] = ..., border_dash_phase: int = ..., border_width_bottom: int = ..., border_width_left: int = ..., border_width_right: int = ..., border_width_top: int = ..., horizontal_alignment: LayoutElement.HorizontalAlignment = ..., margin_bottom: int = ..., margin_left: int = ..., margin_right: int = ..., margin_top: int = ..., padding_bottom: int = ..., padding_left: int = ..., padding_right: int = ..., padding_top: int = ..., sizes: typing.Optional[typing.List[typing.Tuple[int, int]]] = ..., vertical_alignment: LayoutElement.VerticalAlignment = ...) -> None:
        """
        Initialize a new CircularLayoutElementGroup object for rendering a group of LayoutElements in a PDF.

        This constructor allows customization of various layout and style properties
        for the group, such as margins, padding, borders, and alignment. These properties
        define the appearance and positioning of the group within the PDF page.

        :param layout_elements:         The LayoutElement objects in this group
        :param background_color:        Optional background color for the list container.
        :param border_color:            Optional border color for the list container.
        :param border_dash_pattern:     Dash pattern used for the list border lines.
        :param border_dash_phase:       Phase offset for the dash pattern in the list borders.
        :param border_width_bottom:     Width of the bottom border of the list.
        :param border_width_left:       Width of the left border of the list.
        :param border_width_right:      Width of the right border of the list.
        :param border_width_top:        Width of the top border of the list.
        :param horizontal_alignment:    Horizontal alignment of the list (default is LEFT).
        :param margin_bottom:           Space between the list and the element below it.
        :param margin_left:             Space between the list and the left page margin.
        :param margin_right:            Space between the list and the right page margin.
        :param margin_top:              Space between the list and the element above it.
        :param padding_bottom:          Padding inside the list container at the bottom.
        :param padding_left:            Padding inside the list container on the left side.
        :param padding_right:           Padding inside the list container on the right side.
        :param padding_top:             Padding inside the list container at the top.
        :param sizes:                   The (absolute) sizes of the LayoutElements in this group
        :param vertical_alignment:      Vertical alignment of the list (default is TOP).
        """
        ...
    


