"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.color.color import Color
from borb.pdf.layout_element.layout_element import LayoutElement
from borb.pdf.page import Page

"""
A group of layout elements arranged with specified positions and sizes.

This class represents a collection of `LayoutElement` objects, each placed at a
specific position and with a defined size. It extends `LayoutElement` and supports
rendering onto a `Page` while respecting layout properties such as alignment,
margins, padding, and borders.
"""
class LayoutElementGroup(LayoutElement):
    """
    A group of layout elements arranged with specified positions and sizes.

    This class represents a collection of `LayoutElement` objects, each placed at a
    specific position and with a defined size. It extends `LayoutElement` and supports
    rendering onto a `Page` while respecting layout properties such as alignment,
    margins, padding, and borders.
    """
    def __init__(self, layout_elements: typing.List[LayoutElement], positions: typing.List[typing.Tuple[int, int]], sizes: typing.List[typing.Tuple[int, int]], background_color: typing.Optional[Color] = ..., border_color: typing.Optional[Color] = ..., border_dash_pattern: typing.List[int] = ..., border_dash_phase: int = ..., border_width_bottom: int = ..., border_width_left: int = ..., border_width_right: int = ..., border_width_top: int = ..., horizontal_alignment: LayoutElement.HorizontalAlignment = ..., margin_bottom: int = ..., margin_left: int = ..., margin_right: int = ..., margin_top: int = ..., padding_bottom: int = ..., padding_left: int = ..., padding_right: int = ..., padding_top: int = ..., vertical_alignment: LayoutElement.VerticalAlignment = ...) -> None:
        """
        Initialize a new LayoutElementGroup object for rendering a group of LayoutElements in a PDF.

        This constructor allows customization of various layout and style properties
        for the group, such as margins, padding, borders, and alignment. These properties
        define the appearance and positioning of the group within the PDF page.

        :param layout_elements:         The LayoutElement objects in this group
        :param positions:               The (relative) positions of the LayoutElements in this group
        :param sizes:                   The (absolute) sizes of the LayoutElements in this group
        :param background_color:        Optional background color for the list container.
        :param border_color:            Optional border color for the list container.
        :param border_dash_pattern:     Dash pattern used for the list border lines.
        :param border_dash_phase:       Phase offset for the dash pattern in the list borders.
        :param border_width_bottom:     Width of the bottom border of the list.
        :param border_width_left:       Width of the left border of the list.
        :param border_width_right:      Width of the right border of the list.
        :param border_width_top:        Width of the top border of the list.
        :param horizontal_alignment:    Horizontal alignment of the list (default is LEFT).
        :param margin_bottom:           Space between the list and the element below it.
        :param margin_left:             Space between the list and the left page margin.
        :param margin_right:            Space between the list and the right page margin.
        :param margin_top:              Space between the list and the element above it.
        :param padding_bottom:          Padding inside the list container at the bottom.
        :param padding_left:            Padding inside the list container on the left side.
        :param padding_right:           Padding inside the list container on the right side.
        :param padding_top:             Padding inside the list container at the top.
        :param vertical_alignment:      Vertical alignment of the list (default is TOP).
        """
        ...
    
    def get_size(self, available_space: typing.Tuple[int, int]) -> typing.Tuple[int, int]:
        """
        Calculate and return the size of the layout element based on available space.

        This function uses the available space to compute the size (width, height)
        of the layout element in points.

        :param available_space: Tuple representing the available space (width, height).
        :return:                Tuple containing the size (width, height) in points.
        """
        ...
    
    def paint(self, available_space: typing.Tuple[int, int, int, int], page: Page) -> None:
        """
        Render the layout element onto the provided page using the available space.

        This function renders the layout element within the given available space on the specified page.

        :param available_space: A tuple representing the available space (left, top, right, bottom).
        :param page:            The Page object on which to render the LayoutElement.
        :return:                None.
        """
        ...
    


