"""
This type stub file was generated by pyright.
"""

from borb.pdf.font.font import Font
from borb.pdf.primitives import name

"""
Represents a simple font and its properties in a PDF document.

The `SimpleFont` class encapsulates the basic characteristics of a font used in PDF
documents. It provides common properties and methods for working with fonts, such as
character mappings, font metrics, and rendering capabilities. This class serves as the
foundation for more specialized font classes (e.g., `Type1Font`), offering basic font
functionality while allowing for more specific implementations. Simple fonts are used
in a variety of contexts, from basic text rendering to complex document layouts.
"""
class SimpleFont(Font):
    """
    Represents a simple font and its properties in a PDF document.

    The `SimpleFont` class encapsulates the basic characteristics of a font used in PDF
    documents. It provides common properties and methods for working with fonts, such as
    character mappings, font metrics, and rendering capabilities. This class serves as the
    foundation for more specialized font classes (e.g., `Type1Font`), offering basic font
    functionality while allowing for more specific implementations. Simple fonts are used
    in a variety of contexts, from basic text rendering to complex document layouts.
    """
    def __init__(self) -> None:
        """
        Initialize a SimpleFont instance.

        The `SimpleFont` class represents a base class for simple fonts in a PDF. Simple fonts
        use a single-byte encoding for character codes, with support for character mapping through
        encodings, differences, or CMaps.

        This constructor initializes the font with default properties, allowing it to be customized
        or extended to represent specific font types.
        """
        ...
    
    def get_encoding_or_base_encoding(self) -> name:
        """
        Retrieve the encoding or base encoding of the Simple Font.

        This method determines the encoding used by the font, prioritizing the following cases:
        1. If `/Encoding` is a dictionary and contains a `/BaseEncoding` key, the value of `/BaseEncoding`
           (a `name` object) is returned.
        2. If `/Encoding` is directly a `name` object, it is returned as the font's encoding.
        3. If neither of the above is present, the method defaults to `StandardEncoding`, which is the
           common default for simple fonts.

        This logic ensures that the correct encoding is used, whether explicitly defined or falling back
        to a standard default.

        :return: The encoding or base encoding of the font as a `name` object.
        """
        ...
    
    def get_width(self, text: str, character_spacing: float = ..., font_size: float = ..., word_spacing: float = ...) -> int:
        """
        Return the total width of a text string when rendered with the font at a specific size.

        This function calculates the width of the given text string when rendered with the font
        at the specified font size.

        :param font_size:           The font size to be used for rendering.
        :param text:                The text string to calculate the width for.
        :param word_spacing:        The word spacing to be used for rendering
        :param character_spacing:   The character spacing to be used for rendering
        :return:                    The width (in points) of the text in the specified font size.
        """
        ...
    


