"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.font.font import Font

"""
Represents the standard 14 fonts used in PDF documents.

This utility class handles the standard 14 fonts, which include commonly used fonts
such as Helvetica, Times, and Courier. It provides methods to retrieve these fonts
by their names.
"""
class Standard14Fonts:
    """
    Represents the standard 14 fonts used in PDF documents.

    This utility class handles the standard 14 fonts, which include commonly used fonts
    such as Helvetica, Times, and Courier. It provides methods to retrieve these fonts
    by their names.
    """
    @staticmethod
    def get(name: str) -> typing.Optional[Font]:
        """
        Retrieve a font by its name from the standard 14 PDF fonts.

        This method searches for the specified font name among the standard 14 PDF fonts
        and returns the corresponding Font object if found.

        :param name:    The name of the font to retrieve.
        :return:        The matching Font object if found; otherwise, None.
        """
        ...
    


