"""
This type stub file was generated by pyright.
"""

import pathlib
import typing
from borb.pdf.font.font import Font
from borb.pdf.font.simple_font.simple_font import SimpleFont

"""
Represents a TrueType font and its properties in a PDF document.

The `TrueTypeFont` class encapsulates the characteristics of a TrueType font, a
popular font format used in PDF documents. TrueType fonts are known for their
scalability and precise control over font rendering, making them ideal for high-quality
text display. This class provides access to font-specific properties, such as glyph
mappings, font metrics, and rendering capabilities, allowing for accurate text layout
and display in PDF documents. As a subclass of `Font`, it extends the basic functionality
of a font while offering specialized handling for TrueType fonts.
"""
class TrueTypeFont(SimpleFont):
    """
    Represents a TrueType font and its properties in a PDF document.

    The `TrueTypeFont` class encapsulates the characteristics of a TrueType font, a
    popular font format used in PDF documents. TrueType fonts are known for their
    scalability and precise control over font rendering, making them ideal for high-quality
    text display. This class provides access to font-specific properties, such as glyph
    mappings, font metrics, and rendering capabilities, allowing for accurate text layout
    and display in PDF documents. As a subclass of `Font`, it extends the basic functionality
    of a font while offering specialized handling for TrueType fonts.
    """
    @staticmethod
    def from_file(where_from: typing.Union[str, pathlib.Path]) -> Font:
        """
        Create a Font instance from a TrueType font file.

        :param where_from:  The file path to the TrueType font file. Can be provided as a string or a `pathlib.Path` object.
        :return:            An instance of the Font class representing the loaded TrueType font.
        """
        ...
    


