"""
This type stub file was generated by pyright.
"""

"""
Represents the Adobe Glyph List (AGL) for mapping glyph names to Unicode values.

The `AdobeGlyphList` class provides functionality for interpreting and managing glyph
names as specified by the Adobe Glyph List (AGL). The AGL is a widely used standard
for mapping glyph names to their corresponding Unicode values, facilitating text
encoding and rendering in PDF and other document formats.

This class serves as a utility for converting between glyph names and Unicode, allowing
developers to handle text rendering with proper character encoding. It includes methods
to retrieve Unicode values for given glyph names, ensuring that characters are displayed
accurately when rendering PDF content or processing textual data.

The Adobe Glyph List is particularly useful when working with non-standard fonts or
special characters that require explicit mapping to Unicode.
"""
class AdobeGlyphList:
    """
    Represents the Adobe Glyph List (AGL) for mapping glyph names to Unicode values.

    The `AdobeGlyphList` class provides functionality for interpreting and managing glyph
    names as specified by the Adobe Glyph List (AGL). The AGL is a widely used standard
    for mapping glyph names to their corresponding Unicode values, facilitating text
    encoding and rendering in PDF and other document formats.

    This class serves as a utility for converting between glyph names and Unicode, allowing
    developers to handle text rendering with proper character encoding. It includes methods
    to retrieve Unicode values for given glyph names, ensuring that characters are displayed
    accurately when rendering PDF content or processing textual data.

    The Adobe Glyph List is particularly useful when working with non-standard fonts or
    special characters that require explicit mapping to Unicode.
    """
    ADOBE_CHARACTER_NAME_TO_CHARACTER = ...
    ADOBE_CHARACTER_TO_CHARACTER_NAME = ...


