name: Tests CI/CD

on:
  push:
    branches: [ main, sprint* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -f app/Dockerfile.app -t intranet-app .
    
    - name: Run tests in Docker container
      run: |
        docker run --rm \
          -e TESTING=true \
          -e SECRET_KEY=test-secret-key-for-ci \
          -v ${{ github.workspace }}/test:/app/test \
          -v ${{ github.workspace }}/app:/app/app \
          intranet-app \
          bash -c "pip install pytest pytest-flask pytest-cov pytest-mock && cd /app/test && pytest -v --cov=../app --cov-report=term-missing --cov-report=xml"
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./test/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run security scan with bandit
      run: |
        pip install bandit
        bandit -r app/ -f json -o bandit-report.json || true
    
    - name: Upload security scan results
      uses: actions/upload-artifact@v4
      with:
        name: security-scan-results
        path: bandit-report.json

  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety
    
    - name: Check for security vulnerabilities
      run: |
        pip install -r requirements.txt
        safety check --json --output safety-report.json || true
    
    - name: Upload dependency check results
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-results
        path: safety-report.json
