"""
This type stub file was generated by pyright.
"""

import typing
from borb.pdf.color.color import Color
from borb.pdf.color.hsv_color import HSVColor

"""A class that provides static methods to generate color schemes based on the HSV color model."""
class ColorScheme:
    """A class that provides static methods to generate color schemes based on the HSV color model."""
    @staticmethod
    def analogous_colors(base_color: Color, angle_in_degrees: float = ...) -> typing.List[Color]:
        """
        Generate analogous colors for a given color.

        :param base_color:          The base Color.
        :param angle_in_degrees:    The angle (in degrees) between the base color and each analogous color.
        :return:                    A list of two Color objects representing the analogous colors.
        """
        ...
    
    @staticmethod
    def complementary_color(base_color: Color) -> Color:
        """
        Generate the complementary color for a given color.

        :param base_color:  The base color.
        :return:            A new HSVColor object representing the complementary color.
        """
        ...
    
    @staticmethod
    def monochromatic(base_color: Color, steps: int = ...) -> typing.List[HSVColor]:
        """
        Generate a monochromatic color scheme based on a single hue.

        :param base_color:  The base Color to generate the scheme from.
        :param steps:       The number of variations to generate.
        :return:            A list of Color objects in the monochromatic scheme.
        """
        ...
    
    @staticmethod
    def shades(base_color: Color, steps: int = ...) -> typing.List[Color]:
        """
        Generate shades of a given color (mixing with black).

        :param base_color:  The base HSVColor to generate shades from.
        :param steps:       The number of shades to generate.
        :return:            A list of HSVColor objects representing shades.
        """
        ...
    
    @staticmethod
    def split_complementary_colors(base_color: Color, angle: float = ...) -> typing.List[Color]:
        """
        Generate split complementary colors for a given color.

        :param base_color:  The base Color.
        :param angle:       The angle (in degrees) between the base color and each split complementary color.
        :return:            A list of two HSVColor objects representing the split complementary colors.
        """
        ...
    
    @staticmethod
    def square_colors(base_color: Color) -> typing.List[Color]:
        """
        Generate square colors for a given color.

        :param base_color:  The base Color.
        :return:            A list of three Color objects representing the square colors.
        """
        ...
    
    @staticmethod
    def tetradic_colors(base_color: Color) -> typing.List[Color]:
        """
        Generate tetradic (rectangle) colors for a given color.

        :param base_color:  The base Color.
        :return:            A list of three Color objects representing the tetradic colors.
        """
        ...
    
    @staticmethod
    def tints(base_color: Color, steps: int = ...) -> typing.List[Color]:
        """
        Generate tints of a given color (mixing with white).

        :param base_color:  The base Color to generate tints from.
        :param steps:       The number of tints to generate.
        :return:            A list of Color objects representing tints.
        """
        ...
    
    @staticmethod
    def triadic_colors(base_color: Color) -> typing.List[Color]:
        """
        Generate triadic colors for a given color.

        :param base_color:  The base Color.
        :return:            A list of two Color objects representing the triadic colors.
        """
        ...
    


