"""
This type stub file was generated by pyright.
"""

from borb.pdf.color.color import Color

"""
Represents an RGB color space based on the additive RGB color model.

This class defines a color space that employs RGB primaries, characterized by
the chromaticities of red, green, and blue. It can produce any color within the
2D triangle formed by these primary colors (excluding factors like transfer function
and white point).

The primary colors are specified using their CIE 1931 color space chromaticity
coordinates (x, y), linking them to human-visible colors.

RGB stands for red, green, and blue.
"""
class RGBColor(Color):
    """
    Represents an RGB color space based on the additive RGB color model.

    This class defines a color space that employs RGB primaries, characterized by
    the chromaticities of red, green, and blue. It can produce any color within the
    2D triangle formed by these primary colors (excluding factors like transfer function
    and white point).

    The primary colors are specified using their CIE 1931 color space chromaticity
    coordinates (x, y), linking them to human-visible colors.

    RGB stands for red, green, and blue.
    """
    def __init__(self, red: int = ..., green: int = ..., blue: int = ...) -> None:
        """
        Initialize an RGBColor object with specified red, green, and blue values.

        The `RGBColor` class represents a color using the RGB (Red, Green, Blue) model,
        where each component (red, green, blue) is an integer ranging from 0 to 255.
        The color is defined by these three values, which control the intensity of each component.

        :param red:     The intensity of the red component, default is 0. Must be between 0 and 255.
        :param green:   The intensity of the green component, default is 0. Must be between 0 and 255.
        :param blue:    The intensity of the blue component, default is 0. Must be between 0 and 255.
        """
        ...
    
    def get_blue(self) -> int:
        """
        Retrieve the blue component of the RGB color.

        This method returns the blue component as an integer in the range [0, 255].

        :return: The blue component of this RGBColor, as an integer between 0 and 255.
        """
        ...
    
    def get_green(self) -> int:
        """
        Retrieve the green component of the RGB color.

        This method returns the green component as an integer in the range [0, 255].

        :return: The green component of this RGBColor, as an integer between 0 and 255.
        """
        ...
    
    def get_red(self) -> int:
        """
        Retrieve the red component of the RGB color.

        This method returns the red component as an integer in the range [0, 255].

        :return: The red component of this RGBColor, as an integer between 0 and 255.
        """
        ...
    
    def to_hex_str(self) -> str:
        """
        Convert the RGB color to a hexadecimal string representation.

        This method converts the red, green, and blue components of the `RGBColor` instance
        into a hexadecimal string in the format `#RRGGBB`, where each component is represented
        by two uppercase hexadecimal digits.

        :return: A string representing the color in hexadecimal format.
        """
        ...
    
    def to_hsv_color(self) -> HSVColor:
        """
        Convert the RGB color to an HSV color.

        This method converts the red, green, and blue components of the `RGBColor` instance
        into hue, saturation, and value components of the HSV color model.

        :return: A new HSVColor object representing the color in HSV format.
        """
        ...
    
    def to_rgb_color(self) -> RGBColor:
        """
        Convert the current color representation to RGB format.

        This method transforms the current color into an equivalent RGB (Red, Green, Blue)
        representation. It returns a new RGBColor object containing the RGB components of
        the current color.

        :return: A new RGBColor object representing the current color in RGB format.
        """
        ...
    


