"""
This type stub file was generated by pyright.
"""

from borb.pdf.toolkit.event import Event
from borb.pdf.toolkit.pipe import Pipe

"""
A filter class for processing PDF page content streams, specifically targeting content that appears to the right of a specified coordinate on the PDF page.

The `RightOf` filter identifies and processes elements that are located to the right of
a defined x-coordinate threshold. This can be useful for extracting or manipulating content
within a specific horizontal region of the page, such as filtering out text or objects that
appear to the right of a particular point.
"""
class RightOf(Pipe):
    """
    A filter class for processing PDF page content streams, specifically targeting content that appears to the right of a specified coordinate on the PDF page.

    The `RightOf` filter identifies and processes elements that are located to the right of
    a defined x-coordinate threshold. This can be useful for extracting or manipulating content
    within a specific horizontal region of the page, such as filtering out text or objects that
    appear to the right of a particular point.
    """
    def __init__(self, x: int) -> None:
        """
        Initialize a new instance of the `RightOf` filter.

        :param x: The x-coordinate threshold for filtering. Only elements located right of
                  this value will be processed.
        """
        ...
    
    def process(self, event: Event): # -> None:
        """
        Process the given event.

        This base implementation is a no-op. Subclasses should override this method
        to provide specific processing logic.

        :param event: The event object to process.
        """
        ...
    


